### ISSUE TITLE
Exception with SecurityRequirementsOperationFilter when you have already added a 401 or a 403

### ISSUE THREAD

**Issue by korifeich** [mattfrear/Swashbuckle.AspNetCore.Filters#101]
Server error appears when you are trying to access swagger.json file using one of the following combinations response type descriptors inside of the application code together with **SecurityRequirementsOperationFilter**:

`[ProducesResponseType(401)]`

`/// <response code="401">You are not authorized to access this endpoint</response>`

`[ProducesResponseType(403)]`

`/// <response code="403">You are not authorized to access this endpoint</response>`

**Comment by mattfrear** [comment]
Hi

FYI, if you don't want the SecurityRequirementsOperationFilter to automatically add a 401 and a 403, you can tell it not to via:
`options.OperationFilter<SecurityRequirementsOperationFilter>(false);`

**Comment by mattfrear** [comment]
Fix released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-rc5

Thanks for the PR!
