### ISSUE TITLE
[Question] Response example for generic controller

### ISSUE THREAD

**Issue by lamLeX** [mattfrear/Swashbuckle.AspNetCore.Filters#105]
Currently this is my generic controller implementation.
```c#
 [Route("[controller]")]
 [ApiController]
 [ApiVersion("1.0")]
 public class GenericController<T> : ControllerBase where T: IModel
 {
        [HttpPost("", Name = "[controller]_[action]")]
        [SwaggerResponse(StatusCodes.Status201Created, "The item was created."/*, typeof(ViewModel<T>) currently does not allow*/)]
        [SwaggerResponse(StatusCodes.Status400BadRequest, "The item is invalid.")]
        [SwaggerResponse(StatusCodes.Status406NotAcceptable, "The specified Accept MIME type is not acceptable.")]
        public Task<IActionResult> Post(
            [FromServices] IPostCommand<T> command,
            [FromBody] T item,
            CancellationToken cancellationToken) => command.ExecuteAsync(item);
 }
```

Due to the limitation that the Attribute does not support generic type parameter yet.
I cannot tell the `SwaggerResponseAttribute` what response type I want to return.

Is there any work-around so that I can set up the Response example?

Thanks,

**Comment by mattfrear** [comment]
Wow, I've never seen a generic controller before so this is a use case I hadn't considered. I'll have a look when I get a chance.

**Comment by lamLeX** [comment]
I followed this guide https://www.strathweb.com/2018/04/generic-and-dynamically-generated-controllers-in-asp-net-core-mvc/ to implement a generic controller. And everything works correctly. The Request example works correct because it can be inferred by `T`.
However. Since I couldn't change the `IActionResult` into `IActionResult<ViewModel<T>>`. There is no way for me to tell swagger what the response type is.

**Comment by mattfrear** [comment]
It seems that since you can't tell the `SwaggerResponse` attribute (which lives in Swashbuckle.AspNetCore.Annotations, not here) what your response is, then there's no way my library can support your use case. Closing.
