### ISSUE TITLE
SecurityRequirementsOperationFilter removes existing OpenApiSecurityRequirements

### ISSUE THREAD

**Issue by rgylesbedford** [mattfrear/Swashbuckle.AspNetCore.Filters#106]
SecurityRequirementsOperationFilter creates a new list of OpenApiSecurityRequirements rather than appending to the existing list.

**Comment by mattfrear** [comment]
Thanks for the PR. I've done a release https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-rc8
