### ISSUE TITLE
stale readme w/ regards to services.AddSwaggerExamples();

### ISSUE THREAD

**Issue by spottedmahn** [mattfrear/Swashbuckle.AspNetCore.Filters#114]
Under the [installations instructions](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#installation), the part about adding `services.AddSwaggerExamplesFromAssemblyOf<MyExample>();` seems to gotten mangled:

![image](https://user-images.githubusercontent.com/14079228/66485079-2b990580-ea76-11e9-8940-39f440f8e4a5.png)

---

I ran into #56 

>Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Swashbuckle.AspNetCore.Filters.RequestExample' while attempting to activate 'Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter'.

And I see https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/commit/436ad66ee1e4e57be5dc515e39ba5f88aaa80f4d seems to have cleaned it up but apparently things have changed again? `services.AddSwaggerExamples();` has been removed?

**Comment by mattfrear** [comment]
I've removed "either" from the Readme, if that's what was causing the confusion? Thanks for raising.

**Comment by spottedmahn** [comment]
thanks!  gtg 👍
