### ISSUE TITLE
Request examples are not generated if serialize as V2

### ISSUE THREAD

**Issue by TimThrill** [mattfrear/Swashbuckle.AspNetCore.Filters#115]
Request examples are not generated if serialize as V2.
`app.UseSwagger(c =>
{
    c.SerializeAsV2 = true;
});`
It is working fine without this V2 settings.

**Comment by tmarkovski** [comment]
I have the same issue. Any pointers where this can be found in code? I can probably submit a PR

**Comment by APIWT** [comment]
We are running into this one too :) I would love to contribute too, I'll spend a few minutes trying to track down where exactly it breaks down.

**Comment by APIWT** [comment]
Looks like this is actually not possible to accomplish in V2. What a shame!
https://github.com/microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Models/OpenApiExample.cs#L106

**Comment by TimThrill** [comment]
> 
> 
> Looks like this is actually not possible to accomplish in V2. What a shame!
> https://github.com/microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Models/OpenApiExample.cs#L106

Thank you for your exploration. This is indeed frustration.

**Comment by tmarkovski** [comment]
Nooooooo...... :(

**Comment by mattfrear** [comment]
I'll have a look at this when I get a chance, possibly over the Christmas break.

**Comment by mattfrear** [comment]
OK so I just had a quick look at this, and it might be possible to do. Futher investigation needed.

In Swashbuckle.AspNetCore 5 (i.e. OpenApi 3) I populate the example which lives in the `path/requestBody/content/[contentType]/example`.

Back in Swashbuckle.AspNetCore 4 (i.e. swagger v2) era I populated the example which lived on the
`/definitions/[schemaType]/example`, if the `/definitions/[schemaType]` existed. If it didn't, then I fell back to populating the `/path/parameters/[index]/schema/example`.

I suspect (but I need to try it out) that when `SerializeAsV2 = true` is being used, that I might need to populate the `/definitions/[schemaType]/example`. 

One possible problem is that I don't know the value of `SerializeAsV2`, so I'd have to always set `/definitions/[schemaType]/example` even if they are using OpenApi3 - which might then break the examples for OpenApi3. That remains to be seen.

**Comment by joaomajesus** [comment]
We have the same exact issue. 
We use examples but since we use autorest and it needs v2 serialization we need to set SerializeAsV2 = true.

**Comment by mattfrear** [comment]
@joaomajesus - Autorest support OpenApi 3 so maybe you don't need v2 serialization.

I spent a couple of hours looking at this a few months ago, but didn't make much progress.
I think the "fix" might be for our downstream dependencies to "get with the program" and support OpenApi 3, so that we don't need v2 serialization.

This started affecting a project I'm working on when we upgraded to Swashbuckle.AspNetCore 5 in January 2020. I had to use v2 serialization because
1. OpenApi 3 is not supported very well by Azure API Management (in Jan 2020).
2. NSwagStudio which we used for generating clients for our React apps doesn't support OpenApi 3.

I need to re-check my assumptions #1 and #2 to see if that's still the case.

**Comment by joaomajesus** [comment]
@mattfrear Thanks for the feedback! Yes, Autorest supports OpenApi 3 but not the OneOf and AnyOf which is currently a deal breaker.

Please keep us updated. 

Thanks!

**Comment by mattfrear** [comment]
> I suspect (but I need to try it out) that when SerializeAsV2 = true is being used, that I might need to populate the /definitions/[schemaType]/example.

Good news. I've just had a play around and my hunch about populating the `/definitions/[schemaType]/example` works locally.
 
> One possible problem is that I don't know the value of SerializeAsV2, so I'd have to always set /definitions/[schemaType]/example even if they are using OpenApi3 - which might then break the examples for OpenApi3. That remains to be seen.

Confirmed that it is also output in OpenApi3's swagger.json. It's not displayed in swagger-ui which is good, but I don't know if it will break other swagger clients.

I still need to productionize it, add unit tests, etc, but a fix is on the way.

**Comment by mattfrear** [comment]
OK so I was able to workaround this by restoring much of the Swashbuckle.AspNetCore.Filters v4 era code, which sets the example on the /definitions/[schemaType]/example.

This has all the caveats of that code, i.e. you can only have one example per request type, i.e. if say 2 of your controllers have the same object in the request, there will be only one example.

Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.1.1

**Comment by tmarkovski** [comment]
Thank you for powering through this @mattfrear, I appreciate your time.

**Comment by mattfrear** [comment]
Well, this is frustrating. My test projects use Swashbuckle.AspNetCore 5.0.0, so request examples for v2 works with that version of Swashbuckle... but it's not working with the latest (5.3.1).

Reopening...

**Comment by freeranger** [comment]
Hi @mattfrear Did you have any luck with this?  I am hitting this exact issue updating from the old 4.x/Swashbuckle 3.x to 5.1.2 and 5.4.1 respectively.
The request body examples used to work fine with the older versions.

re: not being possible to determine if using V2 or V3 serialisation - perhaps we just need an option on `options.ExampleFilters()` and variations to pass in the same value we pass to `SwaggerOptions.SerializeAsV2` with the onus on us devs to be sure we pass the same value to both?

Thanks

**Comment by mattfrear** [comment]
> Hi @mattfrear Did you have any luck with this? I am hitting this exact issue updating from the old 4.x/Swashbuckle 3.x to 5.1.2 and 5.4.1 respectively.

I got it working locally with Swashbuckle.AspNetCore 5.0.0 and haven't had a chance to have another look at it.

**Comment by mattfrear** [comment]
> re: not being possible to determine if using V2 or V3 serialisation - perhaps we just need an option on `options.ExampleFilters()` and variations to pass in the same value we pass to `SwaggerOptions.SerializeAsV2` with the onus on us devs to be sure we pass the same value to both?

I actually already figured this out - I'm injecting an `IOptions<SwaggerOptions> options` into my filter, and then I can just check `if (swaggerOptions.SerializeAsV2)`.

This worked fine in Swashbuckle.AspNetCore 5.0.0 but seems to be broken now in Swashbuckle.AspNetCore 5.5.1, and is the reason why the fix I released back in April doesn't work. I will raise an issue over there.

**Comment by freeranger** [comment]
Ah, that would come in handy for some of my other use cases too - injecting SwaggerOptions - hopefully you will get an answer on this soon!   Thanks

**Comment by mattfrear** [comment]
OK, someone has posted a workaround to my `SwaggerOptions` issue, which means this defect is finally fixed and can be closed (I hope).

As well as adding
```csharp
            app.UseSwagger(c =>
                c.SerializeAsV2 = true
            );
```

You'll also need to add:
```csharp
services.Configure<SwaggerOptions>(c => c.SerializeAsV2 = true);
```
