### ISSUE TITLE
Upload file filter

### ISSUE THREAD

**Issue by egorowp** [mattfrear/Swashbuckle.AspNetCore.Filters#116]
Hello
I use asp.net core 3.0 with Swashbuckle.AspNetCore package to 5.0.0-RC4
How can I implement UploadFileFilter. Previous implementation don't work.
https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work

**Comment by mattfrear** [comment]
Hi Valery

Unfortunately I don't know. You might want to try asking in the Swashbuckle.AspNetCore GitHub project.
