### ISSUE TITLE
Add support to take in type in AddSwaggerExamplesFromAssemblyOf and not only Generic

### ISSUE THREAD

**Issue by runes83** [mattfrear/Swashbuckle.AspNetCore.Filters#122]
I'm creating a generic swagger module for our company and want to use this package. But the method AddSwaggerExamplesFromAssemblyOf uses generic to get the assembly. It is possible with a lot of reflection to get around that but I was hoping that was possible to add an overload with type as an argument AddSwaggerExamplesFromAssemblyOf(Type type).

I can make a pull request if needed.

**Comment by mattfrear** [comment]
Hi Rune
I don't have a lot of time to spend on this package lately, so a PR is welcome.

It uses the Scrutor package for assembly scanning https://github.com/khellang/Scrutor

**Comment by TWKuanLun** [comment]
Hello...
I was very confused when upgrading to asp.net core 3.1
If I have 200 ~ 300 example classes distributed in different versions, should I have to add 200 ~ 300 AddSwaggerExamplesFromAssemblyOf<thoseExampleClass>() to ConfigureServices in startup?
Is there a smarter way?

**Comment by mattfrear** [comment]
This was fixed in #140 and released in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.2
