### ISSUE TITLE
Cannot use explicit implementation of IExamplesProvider<T>

### ISSUE THREAD

**Issue by alrz** [mattfrear/Swashbuckle.AspNetCore.Filters#130]
The method `InvokeGetExamples` fails to invoke an explicit implementation and throws NRE.
```cs
public class SomeExample : IExamplesProvider<SomeRequest> {
  SomeRequest IExamplesProvider<SomeRequest>.GetExamples() { .. }
}
```

**Comment by Slaviusz** [comment]
Shouldn't you rather stick to the original (and IMO easier) implementation of GetExamples?

`public class SomeExample : IExamplesProvider<SomeRequest> {
    public SomeRequest GetExamples() { return new SomeRequest(); }
}`

**Comment by mattfrear** [comment]
As mentioned in #139, Visual Studio seems to auto implement the interface in the weird explicit implementation.

**Comment by mattfrear** [comment]
I'm going to copy/paste this advisory to any open issues that are for ExamplesOperationFilter.

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#do-not-use-this-filter-unless-you-have-to

Swashbuckle.AspNetCore supports adding examples from XML documentation, which might already cover your use case, in which case you can stop using this package and close your issue.

If examples from XML documentation doesn't work for you, then feel free to leave your issue open.
