### ISSUE TITLE
IExamplesProvider does not respect System.Text.Json.Serialization.JsonPropertyNameAttribute

### ISSUE THREAD

**Issue by ehavelaarsnz** [mattfrear/Swashbuckle.AspNetCore.Filters#132]
In .NET Core 3.1, using 5.0.0, the examples generated by `IExamplesProvider<>` do not respect `System.Text.Json.Serialization.JsonPropertyNameAttribute`

For instance, I have a model object with this property:
``` csharp
[System.Text.Json.Serialization.JsonPropertyNameAttribute ("flc")]
public string FactLifeCycle { get; set; }
```

The example that comes out in the Swagger UI displays this as:
``` json
{
    "factLifeCycle": "RAW"
}
```

But I would expect:

``` json
{
    "flc": "RAW"
}
```

**Comment by CumpsD** [comment]
I'm going to make a small guess and say it is because the example is serialized using Newtonsoft and not system text.

I found this via #136 bumping on: 

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/ee8e231517f7052a96812d3cd9b4c8a8ef62572d/src/Swashbuckle.AspNetCore.Filters/Examples/ResponseExample.cs#L43

**Comment by mattfrear** [comment]
Sounds like a good guess @cumpsD.

I guess someone should change it to use System.Text.Json, and then remove the Newtonsoft dependency. I left it using Newtonsoft because that was the easiest option, and the port to version 5 was a mission.

**Comment by mattfrear** [comment]
I'm going to copy/paste this advisory to any open issues that are for ExamplesOperationFilter.

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#do-not-use-this-filter-unless-you-have-to

Swashbuckle.AspNetCore supports adding examples from XML documentation, which might already cover your use case, in which case you can stop using this package and close your issue.

If examples from XML documentation doesn't work for you, then feel free to leave your issue open.

**Comment by ehavelaarsnz** [comment]
Thanks for the tip, bro
I got nearly all the examples I need using XML documentation.

But how do I mark up an example POST body?  This doesn’t work:
        /// <param name="facts" example="[{var = &quot;I10_VehExp&quot;, uoi = &quot;EN1000&quot;, value = 1500, flc = &quot;RAW&quot;}, {var = &quot;I10_SalWages&quot;, uoi = &quot;EN1000&quot;, value = 56000, flc = &quot;IMPUTED&quot;}]">

Regards,

Ed


Ed Havelaar
Senior Applications Developer
Digital Business Services
Stats NZ Tatauranga Aotearoa
DDI +64 3 964 8757 | stats.govt.nz<http://www.stats.govt.nz/>

**Comment by mattfrear** [comment]
Hi Ed

Your email is encoded and unreadable, so not sure what you're trying to do, but POST body examples can be done like

```csharp
public class Product
{
    /// <summary>
    /// The name of the product
    /// </summary>
    /// <example>Men's basketball shoes</example>
    public string Name { get; set; }

    /// <summary>
    /// Quantity left in stock
    /// </summary>
    /// <example>10</example>
    public int AvailableStock { get; set; }
}
```

**Comment by ehavelaarsnz** [comment]
Hi, thanks for the speedy reply!

My POST body is an array of objects.  The <example> only gives me one element, and I kinda wanted two.
The other hurdle I’m having (hadn’t discovered that yet in previous email) is that one of my properties is declared as type object, which comes out as {} in the generated example.  I’d like to give a numeric example.

Regards,

Ed

Ed Havelaar
Senior Applications Developer
Digital Business Services
Stats NZ Tatauranga Aotearoa
DDI +64 3 964 8757 | stats.govt.nz<http://www.stats.govt.nz/>

**Comment by CumpsD** [comment]
Seems you **do** need this filter then! :D

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#manual-annotation-1
`GetExamples` is your friend for more complex examples

**Comment by JuanZamudioGBM** [comment]
> I'm going to copy/paste this advisory to any open issues that are for ExamplesOperationFilter.
> 
> https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#do-not-use-this-filter-unless-you-have-to
> 
> Swashbuckle.AspNetCore supports adding examples from XML documentation, which might already cover your use case, in which case you can stop using this package and close your issue.
> 
> If examples from XML documentation doesn't work for you, then feel free to leave your issue open.

I tried to use the xml comments instead of the filters, and while I can see the example in UI the generated json files does not include the example object in [content-type].example.

Is there an option that I'm missing?

**Comment by mattfrear** [comment]
> I tried to use the xml comments instead of the filters, and while I can see the example in UI the generated json files does not include the example object in [content-type].example.
> 
> Is there an option that I'm missing?

If you can see it in the UI then it'll be in the json file somewhere. Ctrl-F for it.

**Comment by JuanZamudioGBM** [comment]
I have search for it and found nothing,  in Swagger UI I click on the swagger.json link and none of the examples are there.

I also noticed that in the schema only the summary of the class is added in the documentation, the properties have a default documentation (Represents text as a sequence of UTF-16 code units, Represents a globally unique identifier (GUID)).

**Comment by mattfrear** [comment]
> I have search for it and found nothing, in Swagger UI I click on the swagger.json link and none of the examples are there.
> 
> I also noticed that in the schema only the summary of the class is added in the documentation, the properties have a default documentation (Represents text as a sequence of UTF-16 code units, Represents a globally unique identifier (GUID)).

I don't know. Examples from XML comments is done in the main Swashbuckle.AspNetCore repo not here.

**Comment by mattfrear** [comment]
> Sounds like a good guess @CumpsD.
> 
> I guess someone should change it to use System.Text.Json, ~and then remove the Newtonsoft dependency~. I left it using Newtonsoft because that was the easiest option, and the port to version 5 was a mission.
> 
> Edit: I also just remembered that the `[SwaggerRequestExample]` and `[SwaggerResponseExample]` attributes have a dependency on Newtonsoft so we shouldn't remove it.
> 
> But yeah, for this issue, we should detect which JsonSerializer they have registered and use that.

I've implemented this. The JSON example generation now uses the MvcOutFormatter which @CumpsD first introduced for XML examples. This meant I've dropped the Newtonsoft dependency , and removed the IContractResolver and JsonConverter parameters from [SwaggerRequestExample] and [SwaggerResponseExample].

Because I've removed those parameters, it's a breaking change, so I had to bump the major version number.
https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/6.0.0

**Comment by CumpsD** [comment]
Awesome @mattfrear! Huge improvement
