### ISSUE TITLE
I didn't have to call "services.AddSwaggerExamplesFromAssemblyOf<MyExample>()" for all my examples

### ISSUE THREAD

**Issue by fabio770** [mattfrear/Swashbuckle.AspNetCore.Filters#151]
In the documentation I'm working on, I added Request and Response example filters. In Startup.cs what I realized is that I didn't need to add:

`services.AddSwaggerExamplesFromAssemblyOf<MyExample1>();`

for all my example classes. I only added it once for one Example and it worked normally. Is this behavior expected? Or should it work only when I add for all my request and response examples?

Thanks!

**Comment by mattfrear** [comment]
As the name of the method implies, `AddSwaggerExamplesFromAssemblyOf` adds all detected IExamplesProvider classes that it finds in the assembly of your MyExample1 class.
