### ISSUE TITLE
Unable to setup example for a query parameter of type List<string>

### ISSUE THREAD

**Issue by sturlath** [mattfrear/Swashbuckle.AspNetCore.Filters#152]
I started with an [issue at Swashbuckle.Examples](https://github.com/mattfrear/Swashbuckle.Examples/issues/53) that evolved into using this filter so I'm recreating it here in the correct place.

So my issue is basically that **I can't show an example values for a List<string> in Swagger UI.** My last attempt was to use the [List Request example](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#list-request-examples) like this here below but that doesn't change anything in the UI. 

```csharp
/// <summary>
/// GetById
/// </summary>
[HttpGet]
[SwaggerRequestExample(typeof(string), 
                       typeof(RequestListExample), 
                       jsonConverter: typeof(StringEnumConverter))]
[ProducesResponseType(typeof(ResponseDTO), 200)]
public ResponseDTO GetById([FromQuery] List<string> ids)
{
    return new ResponseDTO() { };
}

// where this is the example 

public class RequestListExample: IExamplesProvider<string>
{
    public string GetExamples()
    {
        return "some id's"; 
    }
}
```
What am I doing wrong here? Must be something tiny I'm missing...

**Comment by mattfrear** [comment]
Hi Sturla

Thanks for opening this issue in the correct repo.
What you are missing is that this package doesn't support examples on the query string at all. It only supports response body examples or request body examples.

I'm sorry that I didn't spot it sooner when you first opened your issue, as you may have noticed I was looking at it on my phone.

**Comment by mattfrear** [comment]
I recently added support for querystring examples to Swashbuckle.AspNetCore in this PR https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1629.

I didn't explicitly add support for lists to that, so if you want Lists to work then you'd need to add it to Swashbuckle.AspNetCore yourself (and submit a PR).

**Comment by sturlath** [comment]
Ok @mattfrear I have nothing better to do over the weekend so how would we represent the example of List<string> ?

Something like this here?

```Csharp
/// <summary>
/// GetById
/// </summary>
// <param name="Ids" example="first|second|third"></param>
public void GetByIds([FromQuery] List<string> ids)
{}
```
