### ISSUE TITLE
Unable to get SwaggerRequestExample to output request examples

### ISSUE THREAD

**Issue by plittlewood-rpt** [mattfrear/Swashbuckle.AspNetCore.Filters#160]
I am in the process of migrating projects to .NET Core 3.1 - as part of our package suite we have a package used for Swagger which makes use of the latest versions of Swashbuckle. To save time, we do not yet want to move to using the `<example>Text</example>` XML example notation and wish to continue using `IExamplesProvider<T>`

I am calling `c.ExampleFilters()` in `services.AddSwaggerGen` and also `services.AddSwaggerExamplesFromAssemblies<T>` but I am only getting examples shown in the generated Swagger for GET requests, so the `SwaggerResponseExample` attribute is being picked up and dealt with accordingly. I cannot get examples to work on write operations (ie POST) despite the controller method being decorated with [SwaggerRequestExample]

If I put a breakpoint in side my implementation of IExamplesProvider for the model used in the POST operation, it does get hit so swagger is at least aware of it.

Am I doing something wrong? Incidentally, calling `services.AddSwaggerExamples()` instead of using the method outlined above results in no examples showing at all (the examples for GET disappear). In addition I can't seem to call `c.OperationFilter<ExamplesOperationFilter>` as the documentation suggests I should do. This causes visual studio to offer to install the Swagger.Examples package which isn't applicable to .NET Core 3.1

**Comment by mattfrear** [comment]
Hi Pete

Please have  a re-read of https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#installation

As you can see, `c.OperationFilter<ExamplesOperationFilter>` is only for old versions.

Also, the call to `services.AddSwaggerExamplesFromAssemblyOf<MyExample>();` should come after `services.AddSwaggerGen(`

Are your request examples in a different assembly than your response examples?

**Comment by plittlewood-rpt** [comment]
Thanks. Noted about the filter, I think I read something on your blog which made me look at that. It may be that I'm calling AddSwaggerExamples.. too early. Will check tomorrow. Thanks for responding

**Comment by plittlewood-rpt** [comment]
Have had a go with this again this morning and no dice. I've forked the filters repo and it seems to be that the SerializeAsV2 config option isn't been respected:

My request pipeline contains 

```
app.UseSwagger(c =>
                c.SerializeAsV2 = true // Ensure we still use v2 spec
            );;
```

Yet when we get to `Swashbuckle.AspNetCore.Filters.SetRequestExampleForOperation` swaggerOptions.SerializeAsv2 is set to false even but the expected example is in scope. 

![image](https://user-images.githubusercontent.com/30798627/94776393-8f1fef80-03b9-11eb-9ade-7d13f25eb045.png)

Will keep hunting unless you've any more suggestions.

**Comment by plittlewood-rpt** [comment]
Can confirm that if I step over line 55 into the if block it does work as intended, so it's something to do with the SerializeAsv2 option not being respected somewhere along the line

**Comment by mattfrear** [comment]
I’m on my phone but search closed issues for serializeasv2.

Matt

**Comment by plittlewood-rpt** [comment]
Happy days. Thanks. Found it - was searching the filters project issues instead of the main one. Workaround described in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1729 resolves it

Thanks!

**Comment by mattfrear** [comment]
Cool. It was also an issue in this project under https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/115.

I've added this to the Installation instructions in the Readme to avoid future confusion.
