### ISSUE TITLE
padlock not showing with AppendAuthorizeToSummaryOperationFilter after IncludeXmlComments

### ISSUE THREAD

**Issue by arisliang** [mattfrear/Swashbuckle.AspNetCore.Filters#164]
According to #74 , if `AppendAuthorizeToSummaryOperationFilter` call is after `IncludeXmlComments`, the padlock should show. But in my case, it still doesn't show. I'm using a more recent version, not sure if related.

>>>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="6.0.1" />
>>>

**Comment by arisliang** [comment]
After added `[Authorize]` to the controller, the `Auth` shows. It doesn't detect global authorize filter though?

**Comment by mattfrear** [comment]
Hi

Nope, it doesn't detect global authorize filters. Last time I looked into it (which was a few years ago), I couldn't see how to detect that a global authorize filter has been registered. Maybe there's a new way now?

**Comment by mattfrear** [comment]
I've added a note to the readme that global authorize filters are not detected.

Closing this issue. Feel free to raise a PR if you would like this fixed.
