### ISSUE TITLE
Request: SwaggerExample should also support the Description-field of OpenApiExample

### ISSUE THREAD

**Issue by penenkel** [mattfrear/Swashbuckle.AspNetCore.Filters#165]
Basically as the title says. I would like to be able to add some descriptions to my examples. Especially as SwaggerUI seems use the summary to populate the selection dropdown (if one is provided).

**Comment by mattfrear** [comment]
Swashbuckle supports using XML comments to add Descriptions https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments

Is there any reason that doesn't work for you?

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.3
