### ISSUE TITLE
Support adding example at the class/schema level rather than per operation

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [mattfrear/Swashbuckle.AspNetCore.Filters#168]
(I have code written to support this and will submit a PR shortly)

I want to be able to set an example when defining a class that is used as a request or response for an operation. I reuse this class in several places so would like to define the example once instead of setting it as `[SwaggerResponseExample(200, typeof(MyExample))]` on every operation where the schema is used. This clutters up my code and tends to be forgotten by developers.

I want to be able to set `SwaggerSchemaExample` on the class and have that be included on the schema and propagated to where the schema is used. The example set on the class should be overwritten by an example set on the operation, so any `SwaggerResponseExample` would supersede a `SwaggerSchemaExample` for the same type.

**Comment by mattfrear** [comment]
Hello

> I want to be able to set an example when defining a class that is used as a request or response for an operation. I reuse this class in several places so would like to define the example once instead of setting it as `[SwaggerResponseExample(200, typeof(MyExample))]` on every operation where the schema is used. This clutters up my code and tends to be forgotten by developers.

You don't need to explicitly specify `SwaggerResponseExample`, I have not done that in my applications for many years. See "Automatic annotation" in the Readme.

> I want to be able to set `SwaggerSchemaExample` on the class and have that be included on the schema and propagated to where the schema is used. The example set on the class should be overwritten by an example set on the operation, so any `SwaggerResponseExample` would supersede a `SwaggerSchemaExample` for the same type.

This behaviour should already happen - you can use automatic annotation to be the default, but then if you want to specify a specific different example then you can use `SwaggerResponseExample` to overwrite the automatic annotation.

**Comment by mattfrear** [comment]
FYI, I used to specify **request**  examples at the schema level in older versions, but I moved away from that when OpenApi 3.0 came out, because users were wanting to override the examples for specific operations.
