### ISSUE TITLE
Mark types public instead of internal to enable extending this with custom filters

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [mattfrear/Swashbuckle.AspNetCore.Filters#169]
I had to write a very similar filter to `ServiceProviderExamplesOperationFilter` and wasn't able to reuse several classes and extensions because they are marked internal instead of public.

My use case is that we have a generic type wrapper for PATCH body parameters which do some logic to determine if a property was set to null or was not included, so an endpoint would look something like this:

```cs
        [HttpPatch("events/{event_id}")]
        [SwaggerRequestExample(typeof(EditEvent), typeof(EventEditExample))]
        public async Task<OkResult> EditEventAsync(
            [FromRoute(Name = "event_id")] string eventId,
            [FromBody, Required] Changes<EditEvent> changes,
            CancellationToken cancellationToken)
        {
            ...
            return Ok();
        }
```

The `ServiceProviderExamplesOperationFilter` only works for automatic example inclusion when the type of the parameter has an `IExamplesProvider`. That doesn't work in this case because the parameter is `Changes<EditEvent>` instead of just `EditEvent`. Changes has no properties and does serialization and deserialization of the request body so I would not be able to make an `IExamplesProvider<Changes>` that is useful. 

I created an `IOperationFilter` that is almost identical to the `ServiceProviderExamplesOperationFilter` but the logic looks for the generic type of `Changes<T>` in the parameter:

```cs
        private void SetRequestExamples(OpenApiOperation operation, OperationFilterContext context)
        {
            var actionAttributes = context.MethodInfo.GetCustomAttributes<SwaggerRequestExampleAttribute>();

            foreach (var parameterDescription in context.ApiDescription.ParameterDescriptions)
            {
                if (!parameterDescription.Type.IsGenericType || parameterDescription.Type.GetGenericTypeDefinition() != _changesType)
                {
                    continue; // We only care about Changes<T> in this filter
                }

                if (actionAttributes.Any(a => a.RequestType == parameterDescription.Type))
                {
                    continue; // if [SwaggerRequestExample] is defined, then let ExamplesOperationFilter define the example
                }

                if (actionAttributes.Any(a => _changesType.MakeGenericType(a.RequestType) == parameterDescription.Type))
                {
                    continue; // if [SwaggerRequestExample(Changes<T>)] is defined, then let ExamplesOperationFilter define the example
                }

                var actualParamType = parameterDescription.Type.GetGenericArguments().First();

                var example = _serviceProvider.GetExampleForType(actualParamType);

                _requestExample.SetRequestExampleForOperation(operation, context.SchemaRepository, actualParamType, example);
            }
        }
```

in order to do this, I had to copy the following files:

- ExamplesConverter
- MvcOutputFormatter
- ObjectExtensions
- OpenApiRawString
- OperationFilterContextExtensions
- RequestExample
- ServiceProviderExtensions
- TypeExtensions

Can these classes be `public` instead of `internal`? Why were they set to `internal` originally?

**Comment by mattfrear** [comment]
Did you try use automatic annotation and implement a  `IExamplesProvider<Changes<EditEvent>>`?

To answer your question about why those types are `internal` rather than `public`. Two reasons - 1. internal is the default when you add a class in Visual Studio, so I didn't give it too much thought about changing it, and 2. I wanted to keep my API's public contract as small as possible. I thought that is a best practice, but I might be mistaken.

**Comment by Blackbaud-ChristiSchneider** [comment]
Unfortunately an `IExamplesProvider<Changes<T>>` wouldn't work in this case because `Changes` has no properties and is doing some fancy stuff with serialization in order to determine if a property is set to null or is not included. It uses a custom input formatter to do this.

**Comment by mattfrear** [comment]
Hi Christi

Sorry for the lengthy delay in replying - I thought I'd already replied but I hadn't. It's a busy time of year.

I've thought about it, and I'm sorry but (for now) I am reluctant to make `internal` types `public`.
- I don't want to increase the public API surface of my library
- it is a breaking change which would require a major version bump

You're the first person who's asked to make them public, but your use case is very specific.
