### ISSUE TITLE
Support options.DescribeEnumsAsStrings

### ISSUE THREAD

**Issue by mattfrear** [mattfrear/Swashbuckle.AspNetCore.Filters#17]
Swashbuckle has options
```
                c.DescribeAllEnumsAsStrings();
                c.DescribeAllParametersInCamelCase();
                c.DescribeStringEnumsInCamelCase();
```

We should support those instead of taking in serializer settings on the attributes

**Comment by ThaynaraSantos** [comment]
The package already have suport to c.SchemaFilter<SomeSchemaFilter>()?

**Comment by mattfrear** [comment]
Nope, at the moment all of my filters are OperationFilters. Maybe they should be SchemaFilters instead. Hmm, you've given me something to think about.

**Comment by ThaynaraSantos** [comment]
Yes, because with SchemaFilter we can use others conventions like snake_case and PascalCase.

**Comment by bhugot** [comment]
Hi, I think with my PR #22 it's should be working

**Comment by mattfrear** [comment]
Hi @bhugot, nope, it doesn't seem to be working even with your PR.
In my sample project, I have added `c.DescribeAllEnumsAsStrings();` and `[SwaggerResponseExample(200, typeof(PersonResponseExample))]` on my controller, but I still only see the Title enum as an int - I need to specify `[SwaggerResponseExample(200, typeof(PersonResponseExample), jsonConverter: typeof(StringEnumConverter))]` to view the Title enum as a string.

**Comment by bhugot** [comment]
Did you added StringEnumConverter to the mvc config

```csharp
services.AddMvc().AddJsonOptions(options =>
{
      options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
}
```

**Comment by mattfrear** [comment]
Ah OK. Your suggestion will change the enum output in the response from the API and swagger's enum output.

But Swashbuckle's `DescribeAllEnumsAsStrings` will only change the swagger output. So if you set `DescribeAllEnumsAsStrings` your API will continue to render enums as ints, but the Swagger should output them as strings.

**Comment by mattfrear** [comment]
I'm not going to get around to doing this, so I'm closing.
