### ISSUE TITLE
Swagger Request Examples for Jtoken Type

### ISSUE THREAD

**Issue by sonamgupta28** [mattfrear/Swashbuckle.AspNetCore.Filters#170]
This might sound a newbie question as I new to swashbuckle but,
I have to create a  swagger request example for the below method:

  public async Task<IActionResult> CreateSomeObject([FromBody] JToken anyToken)
        {
}

But as I searched I found the examples for JObject but not for JToken. Is it not supported? I have a dynamic payload and the data gets saved in influx so I cannot take a custom type for create.

Can some one help me please.

**Comment by mattfrear** [comment]
I'm not familiar with JTokens, but I just tried it and it works.

controller:
```csharp
        [HttpGet("jtoken")]
        public void CreateSomeObject([FromBody]JToken anyToken)
        {
        }
```

example:
```csharp
    public class JTokenExample : IExamplesProvider<JToken>
    {
        public JToken GetExamples()
        {
            var blah = new { blah = "abcd" };
            return JToken.FromObject(blah);
        }
    }
```

![image](https://user-images.githubusercontent.com/169179/104511081-146d9e00-5651-11eb-8f14-2803d0ef34f1.png)

Please re-read the installation instructions as you must not have configured something correctly.

I don't have time for any more support.

**Comment by sonamgupta28** [comment]
Thanks matt..I tried this but i need datatype for the attribute like string/int etc 
example below: 

{
"blah":"string"
}
