### ISSUE TITLE
ExamplesProvider does not work with ProducesDefaultResponseType attribute

### ISSUE THREAD

**Issue by mattwcole** [mattfrear/Swashbuckle.AspNetCore.Filters#171]
Hi, I am using examples providers to document my API and it is working well except one small issue:

- `[ProducesResponseType(typeof(MyResource), StatusCodes.SomeStatus)]` picks up my example
- `[ProducesDefaultResponseType(typeof(MyResource))]` does not

I am adding the attributes to a [conventions class](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-5.0#create-web-api-conventions), but the same problem is present when adding them directly to action methods.

I am forced to use ExamplesProvider over xml comments because it appears to be the only way to get Swashbuckle to use a custom serializer for examples (see [this problem](https://stackoverflow.com/questions/59902076/add-custom-serializer-to-swagger-in-my-net-core-api)).

**Comment by mattfrear** [comment]
Hi Matt

I don't think I've seen `ProducesDefaultResponseType` before. It should be easy to add support for this. I'll try add it in the next week or so if I have time.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/6.1.0
