### ISSUE TITLE
MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2...

### ISSUE THREAD

**Issue by unchase** [mattfrear/Swashbuckle.AspNetCore.Filters#172]
After updating nuget-dependencies to:

![image](https://user-images.githubusercontent.com/29679226/107112574-ae4bf380-6869-11eb-8672-cdce2fc279a3.png)

I have an exception related to this package:

![image](https://user-images.githubusercontent.com/29679226/107112549-88beea00-6869-11eb-821b-62cbf14d6ac5.png)

**Comment by mattfrear** [comment]
Hmm, I haven't tried testing my library with Swashbuckle.AspNetCore v6.0.0 yet. But I have seen that exception a few times in the past - perhaps have a search through the Closed Issues in this repo to see if there are any solutions there.

I'll have a look at this when I have time.

**Comment by mattfrear** [comment]
OK so I just tried to reproduce this, and it's working fine for me.

Attempt 1
- Create new .NET Core 3.1 application
- Install Swashbuckle.AspNetCore latest (6.0.5)
- Install Swashbuckle.AspNetCore.Filters
- Add WeatherForecastExample, works fine

Attempt 2
- Create new .NET 5 application
- Upgrade Swashbuckle.AspNetCore to latest (6.0.5)
- Install Swashbuckle.AspNetCore.Filters
- Add WeatherForecastExample, works fine

Can you be more specific as to what version of .NET you're using?

**Comment by mattfrear** [comment]
Maybe ExcludeAssets might fix it?

`<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="6.1.0" ExcludeAssets="All" />`

**Comment by mattfrear** [comment]
It's also possible that this was fixed in Swashbuckle.AspNetCore 6.0.5.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1998

**Comment by unchase** [comment]
> It's also possible that this was fixed in Swashbuckle.AspNetCore 6.0.4.
> 
> [domaindrivendev/Swashbuckle.AspNetCore#1998](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1998)

Most probably.

Now it's working fine with Swashbuckle.AspNetCore 6.0.5
