### ISSUE TITLE
Examples/annotations are not generated for XML comments for classes outside of the swagger host project

### ISSUE THREAD

**Issue by vflame** [mattfrear/Swashbuckle.AspNetCore.Filters#175]
The XML/annotations/comments of referenced/library projects are not generated, even though all *.csproj are set to generate XML with:
```
 <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
```

Given the following class:

```c#
 public class FFF
    {
        /// <summary>
        /// asdf
        /// </summary>
        /// <example>fff</example>
        public string FA { get; set; }
    }
```

Generated swagger if `FFF` class is in the same project as the swagger host app:
```
"FFF": {
        "type": "object",
        "properties": {
          "fa": {
            "type": "string",
            "description": "asdf",
            "nullable": true,
            "example": "fff"
          }
        },
        "additionalProperties": false
      }
```

Generated swagger if `FFF` class is in another project referenced by the swagger host app:

```
"FFF": {
        "type": "object",
        "properties": {
          "fa": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
```

I can confirm the *.xml file is generated properly.

**Comment by mattfrear** [comment]
This is covered in the installation instructions https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#installation

Make an additional call to 
` services.AddSwaggerExamplesFromAssemblyOf<MyExample>();`

**Comment by mattfrear** [comment]
Oh sorry, I didn't properly read your issue.

The code here doesn't do XML examples, that code lives in https://github.com/domaindrivendev/Swashbuckle.AspNetCore so you should raise an issue over there.
