### ISSUE TITLE
Break interfaces into Abstractions package

### ISSUE THREAD

**Issue by buvinghausen** [mattfrear/Swashbuckle.AspNetCore.Filters#177]
I would like to have Swashbuckle.AspNetCore.Filters.Abstractions so that I can have my plugins be able to write classes using the IExamplesProvider interface without having to also take dependencies on Swashbuckle, Scrutor, & Newtonsoft.Json all of which are hosting level concerns that don't pertain to the plugins.

I'm happy to take a stab at this if you are amenable to it so let me know.

**Comment by mattfrear** [comment]
Yeah sure go for it.

**Comment by mattfrear** [comment]
Merged in with #179

**Comment by mattfrear** [comment]
Released in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.2 
and 
https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters.Abstractions/7.0.0
