### ISSUE TITLE
[Question] When does the assembly scan for examples occur?

### ISSUE THREAD

**Issue by lonix1** [mattfrear/Swashbuckle.AspNetCore.Filters#184]
The [docs say](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/tree/master#automatic-annotation) for example requests/responses using "automatic annotation":
> Version 4.0 and above supports automatic annotation.

I assume the library performs an assembly scan to find appropriate types.

Is the scan performed on every request, or once during startup and then cached? I searched the source but couldn't find the magic sauce as I'm unfamiliar with it.

I'm asking because if it scans on every request, I'd prefer to use ["manual annotation"](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/tree/master#manual-annotation) even though it's more verbose.

(BTW, I'm upgrading from an older version and this new automatic annotation feature has really cleaned up my code, thanks!)

**Comment by mattfrear** [comment]
It uses the Scrutor library to do the assembly scanning, when you call `services.AddSwaggerExamplesFromAssemblyOf<MyExample>()` during startup.

**Comment by lonix1** [comment]
I'm unfamiliar with Scrutor, but I assume you're implying it scans once and caches (probably to the container)?

**Comment by mattfrear** [comment]
Yep, my understanding is the scanning happens once on startup, and saves the registrations to the ServiceProvider.

**Comment by lonix1** [comment]
Thanks Matt!!!

**Comment by lonix1** [comment]
For anyone else wondering about this, he's right the scan is done on startup and the examples are put [into the container as singletons](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/327c796eb6a3ac076a1a2c170ee5c767345f208c/src/Swashbuckle.AspNetCore.Filters/Extensions/ServiceCollectionExtensions.cs#L16-L18). Really useful feature.
