### ISSUE TITLE
DO NOT USE THIS FILTER UNLESS YOU HAVE TO

### ISSUE THREAD

**Issue by RyanGaudion** [mattfrear/Swashbuckle.AspNetCore.Filters#190]
Hi,

Your readme recommends not using the example filters if you don't have to. Is there anyway to have a different response example to the request example without using example filters as I haven't found a way to do this with 'raw' swashbuckle yet.

        [ProducesResponseType(typeof(PersonViewmodel), 200)]
        [SwaggerResponseExample(200, typeof(PersonResponseVmExample))]
        [ProducesResponseType(typeof(string), 400)]
        [SwaggerRequestExample(typeof(PersonViewmodel), typeof(PersonRequestVmExample))]

Or is this an example of when it'll be acceptable to use filters?

**Comment by mattfrear** [comment]
Hi Ryan
Yes, that sounds like a good use case for my filters.
