### ISSUE TITLE
How to Add multiple response examples with custom data using XML 

### ISSUE THREAD

**Issue by srafay** [mattfrear/Swashbuckle.AspNetCore.Filters#193]
I want to add multiple response examples with my custom data. Readme says that I shouldn't use `IMultipleExamplesProvider<T>` because 

> Since May 2018, Swashbuckle.AspNetCore supports adding examples via XML comments.

So I wanted to ask how do I add multiple response examples with my custom data using XML comments instead of implementing `IMultipleExamplesProvider<T>` to generate the example response data.

Thanks!

**Comment by mattfrear** [comment]
Hi
Last time I looked there was no way to add multiple examples using XML comments, so please go ahead and use my `IMultipleExamplesProvider`.

Matt
