### ISSUE TITLE
Multiple Request example in application/xml format

### ISSUE THREAD

**Issue by askids** [mattfrear/Swashbuckle.AspNetCore.Filters#198]
hi,

We are using this package to provide multiple examples of request payloads for different scenarios on same route. This works fine, when we use application/json as content type. But my WebAPI is supposed to accept both XML and JSON formats. When I change content type to application/xml in Swagger UI, it does not generate the XML example for request payload. If I manually create the XML request payload and paste it, the API itself works fine from Swagger. So can you please guide on how to get the XML request example working?

Thanks!

**Comment by mattfrear** [comment]
Hi asskids

If you download the source for this project and run one of the included test projects (e.g. WebApi3.1-Swashbuckle5), it works.

![image](https://user-images.githubusercontent.com/169179/157799436-75cce8e5-ef94-4f84-b54a-67d74128264a.png)

![image](https://user-images.githubusercontent.com/169179/157799503-cf0c8320-343c-4a8d-bf70-4d4442f4090b.png)

You just need to specify XML like:
```csharp
services.AddControllers()
    .AddJsonOptions(opt => opt.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()))
    .AddXmlSerializerFormatters();
    // .AddXmlDataContractSerializerFormatters(); or like this
```

Matt

**Comment by askids** [comment]
hi @mattfrear 

I have it as below. I am using IMultipleExampleProvider.to provide different request examples.
```
services.AddControllers()
                    .AddXmlSerializerFormatters()
                    .AddXmlDataContractSerializerFormatters();
```
But when I switch from application/json to application/xml, I am getting below error stating XML cannot be generated. I have XmlRoot annotation added to the top of the Model class that is being used for the request payload. But still getting this error.

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML example cannot be generated; root element name is undefined -->

```

Thanks!

**Comment by mattfrear** [comment]
I don't think you need both `AddXmlSerializerFormatters` and `AddXmlDataContractSerializerFormatters`, you probably only need one or the other.

Hmm, I don't know. If you download the source code for this repository and run one of my included test projects, you'll see multiple examples works OK in XML:
![image](https://user-images.githubusercontent.com/169179/161605976-c70cee85-5ee3-4b62-8f5a-b119a7a7b0c1.png)
