### ISSUE TITLE
Request Example showing in Response 

### ISSUE THREAD

**Issue by imprathamesh** [mattfrear/Swashbuckle.AspNetCore.Filters#203]
Hi, 

I created example and my post api like this
    [HttpPost]
    public async Task<ActionResult<PurchaseOrder>> PostPurchaseOrder(PurchaseOrder purchaseOrder)
    {
        //code here
    }
Registering the example the examples showing in Response section . 
The parameter section does not change to example as defined.
using asp.net core webapi 6

**Can you defined the installation or Usage Instruction as per ASP.NET Core Versions here on Github. That would be helpful to all community.

**Comment by mattfrear** [comment]
Firstly, for your simple use case, do you even need to use my filter?

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments

> **Can you defined the installation or Usage Instruction as per ASP.NET Core Versions here on Github. That would be helpful to all community.

The instructions are in the Readme file.
See Installation: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#installation

Followed by "How to use": https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#how-to-use
