### ISSUE TITLE
"Request examples are not shown for querystring parameters" clarification in README

### ISSUE THREAD

**Issue by hmoratopcs** [mattfrear/Swashbuckle.AspNetCore.Filters#204]
The README.md states:
> Request examples are not shown for querystring parameters (i.e. HTTP GET requests, or for querystring parameters for POST, PUT etc methods). Request examples will only be shown in request body. This is as per the OpenApi 3.0 spec

I can't find that in the OpenApi 3.0 spec.

Does it mean that the following is not allowed?
```
openapi: 3.0.1
info:
  title: Test
  version: v1
paths:
  /path1:
    get:
      parameters:
        - name: param1
          in: query
          schema:
            type: string
          examples:
            example1:
              value: value1
            example2:
              value: value2
      responses:
        200: 
          description: OK
```

Reading #66 I understand this is a limitation of the filter. Should the sentence `This is as per the OpenApi 3.0 spec` be removed?

**Comment by mattfrear** [comment]
Hello, yes you are correct. It was a limitation of Swagger 2.0 but Open API 3.0 allows it. I will update the readme.
