### ISSUE TITLE
IExamplesProvider doesn't provide example for argument marked [FromQuery], but does for [FromBody]

### ISSUE THREAD

**Issue by ellisonch** [mattfrear/Swashbuckle.AspNetCore.Filters#207]
I have an `IExamplesProvider<Foo>` example that works when I write an endpoint like

```C#
public Task EndpointName([FromBody] Foo inputDto) { ...
```
but doesn't work if I change it to 

```C#
public Task EndpointName([FromQuery] Foo inputDto) { ...
```

I see that there are some warnings in the readme about not being able to provide examples for get parameters in certain circumstances, but I thought using an `IExamplesProvider` would work.  I thought support for get params with an `IExamplesProvider` was added as a result of #66.  Maybe it was only added for `[FromRoute]`?

**Comment by mattfrear** [comment]
Correct, that's by design. I got it working as part of #66 but then decided it's not worth adding.

My thoughts on it are here in this comment. https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/66#issuecomment-616092921

You can use XML comments instead.

**Comment by ellisonch** [comment]
Ah, I see.  I was looking at https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/66#issuecomment-617024609 and thought it would work for `IExamplesProvider`.

I quite like making the examples in code instead of comments, as I'd rather the compiler be able to detect and alert me if I've changed a type but forgot to update the example.  But, I do appreciate the info :)  I'll give it a shot.
