### ISSUE TITLE
Request examples with multiple parameters overwriting each other.

### ISSUE THREAD

**Issue by WillGunn** [mattfrear/Swashbuckle.AspNetCore.Filters#209]
I believe there is a bug around here: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/c96c940e90cfc73b8486a7f23ae4c560a26276ad/src/Swashbuckle.AspNetCore.Filters/Examples/ServiceProviderExamplesOperationFilter.cs#L37-L42

We ran into an issue migrating from swagger v2 to openapi v3 where after switching the swashbuckle generation to write the output files at v3 instead of v2, POST and PUT operations with request bodies were all getting the same incorrect request body example (the model schema was fine).  After debugging, it turned out because we have a header based versioning system, the "api-version" header was in the context.ApiDescription.ParameterDescriptions (as a string type) and it came after the parameter description for the request body, so the example of type "string" was clobbering the actual request body examples for the endpoints.

I'll see if I can modify your tests locally to reproduce the issue, and I'll push up a branch when I do.

For reference here is our services.AddApiVersioning block
`services.AddApiVersioning(
	options =>
	{
		options.ApiVersionReader = new HeaderApiVersionReader("api-version");
		options.AssumeDefaultVersionWhenUnspecified = true; 
		options.ApiVersionSelector = new CurrentImplementationApiVersionSelector(options); 
		options.ReportApiVersions = true; 
	});
`

**Comment by mattfrear** [comment]
Fixed in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.5
