### ISSUE TITLE
Error when using SwaggerRequestExample

### ISSUE THREAD

**Issue by LorisQUE** [mattfrear/Swashbuckle.AspNetCore.Filters#211]
Hello,

I'm currently using Swashbuckle.AspNetCore.Filter 7.0.2 and I have two patch method, that both use a JObject in the request body. Since the JObject provide no example, I've decided to use this package to show the user what can be filled in and what can't. I do believe it can't be done without this package, right ?

So I created two examples that works : The thing is one example appear on a method and the same example appear for the other. 

I then decided to add **SwaggerRequestExample** for both method as a way to specify wich example I desire for one particuliar method.
Just like this: 

```c# [HttpPatch("{code}")]
        [SwaggerRequestExample(typeof(JObject), typeof(fooExample))]
        public IActionResult Patch([FromRoute] string code, [FromBody] JObject foo)
```

```c# [HttpPatch("{code}")]
        [SwaggerRequestExample(typeof(JObject), typeof(barExample))]
        public IActionResult Patch([FromRoute] string code, [FromBody] JObject bar)
```

But unfortunately, when I do that an error occurs while starting the project. 

Could you please help me ?

<details>
  <summary>Screenshots</summary>
  
  ![](https://i.imgur.com/U0rGtXB.png)
The errors

  ![](https://i.imgur.com/9DAIJ2D.png) 
Example of one of my example

</details>

**Comment by mattfrear** [comment]
Can you please paste the entire content of your `IExamplesProvider<JObject>` class instead of the tiny screenshot?

**Comment by mattfrear** [comment]
Sounds like another duplicate of #130

**Comment by LorisQUE** [comment]
Yeah, that was it. Thanks alot and sorry to pollute the issues with dumb questions 😬 
Anyway, great work with the package !
