### ISSUE TITLE
Can't generate multiple response examples for Task<IAction> controller method

### ISSUE THREAD

**Issue by dietowin** [mattfrear/Swashbuckle.AspNetCore.Filters#218]
Hello!
Thank you for the package! 
I'm gonna use it since it looks good for solving my problems, however, I can't understand how to generate multiple response examples.

It works great if I expected to recieve concrete reference type from my method (not Task<IActionResult>).

IMultipleExamplesProvider implementation:
![image](https://user-images.githubusercontent.com/39990617/215545602-1dbb9012-7c76-442e-be97-23e652b8a338.png)

Controller:
![image](https://user-images.githubusercontent.com/39990617/215545434-b68ada1d-8fe2-4712-bc54-e31c770db802.png)

This is my swagger interface:
![image](https://user-images.githubusercontent.com/39990617/215544743-da395303-2d38-45d2-81ac-ec86bbdebc44.png)

This is the .json:
![image](https://user-images.githubusercontent.com/39990617/215544951-90d98c9b-a7de-472c-b510-52740ca869b2.png)

Looks good!

BUT
Problems started when I want to use Task<IActionResult> as a return type with the same IMultipleExamplesProvider implementation.

Controller:
![image](https://user-images.githubusercontent.com/39990617/215546195-d12bc086-3a5f-406e-b7f6-e85a9ea67652.png)

Swagger UI:
![image](https://user-images.githubusercontent.com/39990617/215546132-5ec23e16-f556-4546-94e5-9ed955954437.png)

.json:

![image](https://user-images.githubusercontent.com/39990617/215546327-b2cdabc4-e00b-4cdb-9eb2-2b7f31def123.png)

May be i just need to change my implementation and it should somehow return object wrapped by IActionResult?
Could you help me, please?

**Comment by mattfrear** [comment]
Hi

Try also adding the `[SwaggerResponse]` attribute for your 200 response.

**Comment by dietowin** [comment]
Hi! Thank you for reply! 
Actually, It doesn't look like it is still available. Please, check the first comment below. https://stackoverflow.com/questions/45182448/swashbuckle-swagger-documentation-of-returned-response

I used [ProducesResponseType(typeof(RefreshTokenResponse), 200)] above [SwaggerResponseExample] and it works fine! I think we can end up with it since I solved my problem. Thank you for the help, it was really useful (not sarcastic :))
