### ISSUE TITLE
Provide string[] via param different than on a property (improve documentation)

### ISSUE THREAD

**Issue by Hypenate** [mattfrear/Swashbuckle.AspNetCore.Filters#219]
Via params
```
        /// <summary>
        /// Get items by channel type
        /// </summary>
        /// <param name="channeltype" example="'email">Channels to filter on</param> <-- fails 
        /// <param name="channeltype" example="'['email']">Channels to filter on</param> <-- fails 
        /// <param name="channeltype" example="'[email]">Channels to filter on</param> <-- fails
        /// <param name="channeltype" example='["email"]'>Channels to filter on</param> <-- works
        /// <param name="channeltype" example="[&quot;email&quot;]">Channels to filter on</param> <-- works
        /// <response code="200">Ok</response>
        [HttpGet("channels", Name = "get-restrictions-by-channel")]
        [ProducesResponseType(typeof(ResponseWrapper<RestrictionBaseResponseModel>), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetRestrictionsByChannel([FromQuery] string[] channeltype) { }
```

I also have a model, and there the following works:
```
        /// <summary>
        /// The channels this restriction applies to.
        /// </summary>
        /// <example>["email"]</example>
        public string[] Channels { get; set; }
```

It would be nice that this would be documented, it took my quite some time to figur this one out :)

**Comment by mattfrear** [comment]
XML examples is part of Swashbuckle.AspNetCore and not part of this project. The relevant section is here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments

 You are welcome to add to the documentation for that project by submitting a PR to that project.

**Comment by Hypenate** [comment]
I can 't do a PR for this repo.
![image](https://user-images.githubusercontent.com/7478681/219866459-a0e27073-a74e-4b61-ab66-f7e378a06c3c.png)

Shall I  create a fork?

**Comment by mattfrear** [comment]
Yeah, I think that’s standard GitHub practice Sent from my phoneOn 19/02/2023, at 01:44, Ben ***@***.***> wrote:﻿
I can 't do a PR for this repo.

Shall I  create a fork?
