### ISSUE TITLE
SecurityRequirementsOperationFilter doesnt work with MinimalAPIs

### ISSUE THREAD

**Issue by hartmair** [mattfrear/Swashbuckle.AspNetCore.Filters#227]
`SecurityRequirementsOperationFilter` doesn't pick up `AuthorizeAttribute` in case of Minimal API fluent `.RequireAuthroization()` using Swashbuckle.AspNetCore Version 6.3.0 or later

**Comment by mattfrear** [comment]
Hi @hartmair 

I haven't worked with MinimalApis before. However, this solution does already has a test/MinimalApi6.0 test project.

I am trying to reproduce your issue. As I said, I haven't worked with Minimal Apis so there is a learning curve here for me, but from what I can see, the SecurityRequirementsOperationFilter in master branch already works.

e.g
```csharp
app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
       new WeatherForecast
       (
           DateTime.Now.AddDays(index),
           Random.Shared.Next(-20, 55),
           summaries[Random.Shared.Next(summaries.Length)]
       ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast")
.RequireAuthorization();
```

Renders:
![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/169179/b76f6d60-fe27-4048-ac01-ff731b7fcf3b)

I have updated this test project in master branch, so you can run it and see for yourself.

Can you please explain what is not working?

**Comment by hartmair** [comment]
> from what I can see, the SecurityRequirementsOperationFilter in master branch already works.
> Can you please explain what is not working?

@mattfrear I have updated the description to be more precise: Use the latest version of Swashbuckle.AspNetCore.SwaggerGen. See also the open PR for more details (already rebased since #226 has been merged today)

In MinimalApi6.0-Swashbuckle6.csproj
```diff
-    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
+    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
```

**Comment by mattfrear** [comment]
Hmm, OK. So there's a breaking change in Swashbuckle.AspNetCore then.

The author of that package doesn't usually introduce breaking changes between minor package versions, so I would have investigated it and raised it with him, rather than having to rewrite code in my package.

**Comment by mattfrear** [comment]
Thanks @hartmair for fixing the GetControllerAndActionAttributes method in your PR.
However your PR was a bit too big and too many unrelated changes. In the end all that needed to change was this (I think):  https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/commit/67e7e3f1e5ddae85fceae2ee6e20e322f5f8ff64

Released in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.9

**Comment by hartmair** [comment]
> too many unrelated changes. 

Those "unrelated" changes were to ensure proper unit tests for all different kind of .NET versions and Swashbuckle dependency versions. Since the change in `GetControllerAndActionAttributes` affects all of them.

> your PR was a bit too big

Feel free to take individual commits from https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/228/commits into  small pull requests

**Comment by mattfrear** [comment]
> Feel free to take individual commits from https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/228/commits into small pull requests

Thanks, yeah what you did was good, but wasn't needed for this bug. This project is in maintenance mode so I'm trying not to introduce too many changes.
