### ISSUE TITLE
Using Registered Services in HttpContext that is Used During Example Generation

### ISSUE THREAD

**Issue by aremes** [mattfrear/Swashbuckle.AspNetCore.Filters#230]
So: I have a custom output formatter that requires looking up a few registered services in HttpContext.RequestServices

Due to:

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/3281d65a40320ac1e201e00c8aefef154e0dbef7/src/Swashbuckle.AspNetCore.Filters/Examples/MvcOutputFormatter.cs#L155C21-L155C21

this output formatter fails during examples generation because HttpContext.RequestServices is basically empty.

Would it not be reasonable to inject IServiceProvider into MvcOutputFormatter and do something like
```csharp
httpContext.RequestServices = serviceProvider
```
?

**Comment by mattfrear** [comment]
That sounds like a good idea.

**Comment by aremes** [comment]
I have created a PR for your consideration. Not sure how to test it properly in integration (i.e. one of the WebApi projects under tests/).

**Comment by mattfrear** [comment]
The first thing I do is run one of the projects under test and check that everything looks OK.
So you should be able to run master branch on your localhost, and see a Swagger page with examples etc.
And then run your feature branch and eyeball it and check everything looks OK.

I have your PR and another one to review. I am quite busy but I will try to look them some time in the next 3 weeks.

**Comment by mattfrear** [comment]
Just a note to say I haven't forgotten about this. 

I am on holiday with my family, and I was hoping I would have a chance to look at it during my holiday, but that is unrealistic. So I won't be able to look at this until early September.

Sorry about the delay.

**Comment by aremes** [comment]
Dude, seriously.. no need for an apology and/or justification :D You _are_ doing this without compensation, after all. Enjoy your vacation :)

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/7.0.11
