### ISSUE TITLE
Minimal Api returns examples in Pascal case with no option to change

### ISSUE THREAD

**Issue by kimsagro1** [mattfrear/Swashbuckle.AspNetCore.Filters#237]
If you run the `MinimalApi8` test project, you can see that the example response is Pascal case.

```json
[
  {
    "Date": "2024-01-08T00:00:00+11:00",
    "TemperatureC": 20,
    "Summary": "Sunny",
    "TemperatureF": 67
  }
]
```

![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/6754658/35e956f0-c834-4f21-b3a0-3fe335145c0e)

I assume this is due to `System.Text.Json` using `Pascal Case` by default.

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/3e7e1f47b77eb4ba67b1de2412258d37999b1f64/src/Swashbuckle.AspNetCore.Filters/Examples/MvcOutputFormatter.cs#L108

This behaviour is the opposite of the default example generated by swagger

```json
[
  {
    "date": "2024-01-08T05:49:44.552Z",
    "temperatureC": 0,
    "summary": "string",
    "temperatureF": 0
  }
]
```

Is there any way to configure this?

**Comment by mattfrear** [comment]
Hello. There's a note about camel case in my Readme: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#pascal-case-or-camel-case

The suggested workaround in the readme is:
```csharp
builder.Services.Configure<Microsoft.AspNetCore.Mvc.MvcOptions>(options =>
{
	options.OutputFormatters.Clear();
	options.OutputFormatters.Add(
		new Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter(
			new JsonSerializerOptions
			{
				PropertyNamingPolicy = JsonNamingPolicy.CamelCase
			}));
});
```
The above worked fine with .NET 6, but it throws exceptions in .NET 8.

However, I don't think this should be necessary. 

As you have pointed out, the default from Swagger is camelCase, and the default 200 response is also camel case - so the example should also default to camel case.

I will make these changes soon and push out a new release. 

Unfortunately this is a breaking change for those few folks who want to use Pascal Case in their minimal API examples, which dare I say it means I need to bump the major version number. Hmm. I'm reluctant to make breaking changes so I need to think about this.

**Comment by kimsagro1** [comment]
@mattfrear Thanks for your speedy response. I did try the work around as per the docs but hit the exception (I'm using .NET 8).

**Comment by mattfrear** [comment]
Released a new major version for this https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/8.0.0
