### ISSUE TITLE
ComplexObjects customize response body display values

### ISSUE THREAD

**Issue by marekbe** [mattfrear/Swashbuckle.AspNetCore.Filters#243]
Hi I have an endpoint:
![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/29532981/dea80240-660d-488f-9791-107bf1bdd699)
where example value looks like:
```
{
  "localDate": "Wednesday, 13 March 2024"
}
```

But when I try it out in response I can find whole object
![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/29532981/26422f56-45a8-498d-81e1-0113f5a4ce71)

My endpoint:
```
    [HttpGet("any-simple-random-object")]
    [Produces("application/json")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<ActionResult<AnySimpleObjectResponse>> GetAnySimpleObject()
        => await Task.FromResult(AnySimpleObjectResponse.CreateRandomObject());
        
```
My response:

```
public record AnySimpleObjectResponse(LocalDate LocalDate)
{
    public static AnySimpleObjectResponse CreateRandomObject()
        => new(LocalDate.FromDateTime(DateTime.Now));
}
```

The question is, what should I do to have response displayed only in swagger UI like in example (e.g. for postman I want to see whole object).

I'm looking for general mechanism, I don't want to add any attributes for every potential response object or for all endpoints.

**Comment by mattfrear** [comment]
This sounds like a question for Stackoverflow and not an issue here.
