### ISSUE TITLE
SecurityRequirementsOperationFilter outputs duplicate security in minimal api

### ISSUE THREAD

**Issue by scholtz** [mattfrear/Swashbuckle.AspNetCore.Filters#244]
## Problem

on each access of swagger.json file new security item is inserted

on 4th access it looks like this:
```
"security": [
          {
            "oauth2": [ ]
          },
          {
            "oauth2": [ ]
          },
          {
            "oauth2": [ ]
          },
          {
            "oauth2": [ ]
          }
        ]
```

## Version
Framework: net8.0
Microsoft.AspNetCore.OpenApi: 8.0.3
Swashbuckle.AspNetCore: 6.5.0
Swashbuckle.AspNetCore.Filters: 8.0.1

## Example

https://github.com/scholtz/TestMinimalAPI

![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/1223439/8eeede69-b411-4912-9d5c-a3d96a6ac847)

![image](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/assets/1223439/c96a60b8-653a-42ca-9576-4fe74c18bb94)

## Why is it problem

We want to use the swagger for generated clients and in cicd pipeline on each build of the web api we want to insert into the code repo the generated swagger file which will rebuild the affected shared client. Because on each hit we get different file and will force rebuild of the project.

**Comment by mattfrear** [comment]
I can't reproduce this, and the URL https://github.com/scholtz/TestMinimalAPI gives me a 404 - is it a private repo?

Which of my filters are you using? And how are they configured in Program.cs?

**Comment by scholtz** [comment]
@mattfrear sorry, my mistake, https://github.com/scholtz/TestMinimalAPI is public now.

thanks

**Comment by mattfrear** [comment]
I'm not sure why yet, but this is caused by your usage of `.WithOpenApi();`
