### ISSUE TITLE
Signing key shouldn't be public

### ISSUE THREAD

**Issue by bruno-brant** [mattfrear/Swashbuckle.AspNetCore.Filters#251]
Signing keys must not be public! Currently, anyone can grab your signing key and sign their own assembly, defeating the whole purpose of strong naming: the idea is to prevent code injection in sensitive scenarios where anyone could grab your code (or even the assembly directly), inject their own malicious code, compile and sign it, then replace a valid assembly somewhere with the hacked one.

I want to make the case that it's preferable to not sign the assembly at all if the key is public/leaked, otherwise people might trust that this is a secure assembly when, in fact, it isn't.

**Comment by mattfrear** [comment]
Oh, oops, thanks for pointing that out.

Honestly, I didn't care for strong naming it, but some random guy asked for it because of his corporate policy, so I did it. 

What should I do now? Should I create another key but not expose it this time? Or is it too late?

**Comment by bruno-brant** [comment]
Sorry Matt, it was just pointed out to me that this is no longer the guidance from msft. The key can be public and checked in.

I'll close the issue, but thanks for taking the time to read it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mattfrear** [comment]
OK. Before you close the issue, please add a link to the MSFT reference docs you're referring to.

**Comment by bruno-brant** [comment]
Here it is: https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

The sole purpose is to avoid name clashes.

**Comment by mattfrear** [comment]
Thanks for the link. Interesting.

> Do not rely on strong names for security. They provide a unique identity only.
> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

Sounds like a waste of time then, since this package is .NET Core only.
