### ISSUE TITLE
Time to split up this project?

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.AspNetCore.Filters#32]
Hi,

The project is called "Swashbuckle.AspNetCore.**Examples**" and the purpose seems to be to enable you to generate swashbuckle examples...but now it lets you add an authorization input header box to your page, a file upload button, request headers (e.g. for correlation id) and now response headers too.

These are all very useful features to have, but have nothing at all to do with generating swashbuckle examples...so I wonder if it would make more sense to split that functionality off into a separate project and nuget package and keep Swashbuckle.AspNetCore.Examples purely for generating said swashbuckle examples?

**Comment by mattfrear** [comment]
Well, I don't really want to take on the maintenance burden of having n number of other NuGet packages to manage. I also have the older sister `Swashbuckle.Examples` project to look after, and most changes to this package needs to be ported to that one and vice versa.

Granted, there's not much code here to maintain but I don't have a lot of spare time.

I get what you mean - this package has basically become a dumping ground for stuff I've found handy while using Swashbuckle for the last 3 years or so. If I was going to make any changes, then maybe it should be renamed to something like Swashbuckle.AspNetCore.Contrib. But I'm not sure renaming a NuGet package is a good idea, it would likely cause problems for those already using it. Maybe? I don't know.

I also think it would be a bit silly to have a NuGet package containing only a single class of about 20 lines.

**Comment by freeranger** [comment]
What about one project for Examples and one other project for "everything else", that being a contrib project?
Agreed having a bunch of projects with a handful of lines in them is likely overkill.
You could put out a call for volunteers to help maintain the repos?

**Comment by ChristianSauer** [comment]
I thinkt the examples should be part of Swashbuckle Core, but the project itself is just  not moving at all, so problems like this project are inevitable.

**Comment by mattfrear** [comment]
Rename complete,  I think the new name makes more sense. Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/
