### ISSUE TITLE
not compatible with Swashbuckle >= 3.0

### ISSUE THREAD

**Issue by 0x53A** [mattfrear/Swashbuckle.AspNetCore.Filters#46]
![grafik](https://user-images.githubusercontent.com/4236651/42517511-26d0828a-8460-11e8-9640-870ea3479431.png)

Swashbuckle.AspNetCore [moved a few types around](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/799#issuecomment-403608975).

``SwaggerResponseAttribute`` was moved from ``Swashbuckle.AspNetCore.SwaggerGen`` to ``Swashbuckle.AspNetCore.Annotations``.

Can you please recompile against v3?

Thank you!

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/
