### ISSUE TITLE
Description not working for Arrays

### ISSUE THREAD

**Issue by veler** [mattfrear/Swashbuckle.AspNetCore.Filters#54]
Hi,

I'm using the Description attribute in the models that are part of response or request data.
Unfortunately, if I declare in the root model an Array of a class that has the Description attributes, those are not rendered in the Swagger.json.

Here is a sample : 

```csharp
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpPost]
        public void Post([FromBody]RootModel value)
        {
        }
    }

    public class RootModel
    {
        [Description("This ROOT description works")]
        public SubModelA SubModelA { get; set; }

        [Description("This ROOT description works")]
        public SubModelB[] subModelBs { get; set; }
    }

    public class SubModelA
    {
        [Description("This description works")]
        public string A { get; set; }
    }

    public class SubModelB
    {
        [Description("This description DOESN'T work")]
        public string B { get; set; }
    }
```

And here is the render : 

![capture](https://user-images.githubusercontent.com/3747805/43251122-63b75384-90bf-11e8-9708-0ebd37335534.PNG)

Thanks =)

**Comment by mattfrear** [comment]
OK, I'll have a look.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.0.2

**Comment by veler** [comment]
Thanks :D

**Comment by mattfrear** [comment]
Are you sure? I just tried with
```csharp
    public class RootModel
    {
        [Description("This ROOT description works")]
        public SubModelA SubModelA { get; set; }

        [Description("This ROOT description works")]
        public ICollection<SubModelB> subModelBs { get; set; }
    }
```
and `IEnumerable<SubModelB>`, and both work fine.

![image](https://user-images.githubusercontent.com/169179/43418847-2b619c1c-9437-11e8-8877-f8d20b277716.png)

**Comment by veler** [comment]
Hey,

After more investigation, yes, there is an issue, but not as described.

In fact, the description in `SubModelB ` is not rendered if there is no Description on the list property in the `RootModel`.

Try to `comment/uncomment` the Description attribute on `subModelBs `to see the difference : 

```csharp
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpPost]
        [SwaggerResponse((int)HttpStatusCode.OK, Type = typeof(RootModel))]
        public IActionResult Post()
        {
            return Ok();
        }
    }

    public class RootModel
    {
        //[Description("This description works")]
        public ICollection<SubModelB> subModelBs { get; set; }
    }

    public class SubModelB
    {
        [Description("This description DOESN'T work if the description in RootModel is commented")]
        public string B { get; set; }
    }
```

![capture](https://user-images.githubusercontent.com/3747805/43444199-789fc668-94a3-11e8-93f0-7c68e1f1d2d5.PNG)

**Comment by mattfrear** [comment]
Hehe. Thanks for spotting the bug. If you find any more bugs then please open a new issue.

Fix released in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.0.3
