### ISSUE TITLE
swagger.json generation crashes when a controller operation accepts a nullable Enum as a parameter

### ISSUE THREAD

**Issue by aleksandersmierciak** [mattfrear/Swashbuckle.AspNetCore.Filters#55]
Hello,

I wanted to use Swashbuckle.AspNetCore.Filters to extend the documentation of my WebAPI project and to provide sample requests/responses for faster manual testing via Swagger UI. However, I have encountered issues that I isolated, analysed and further explain below. It may be a bug, it may be a comprehension failure on my part. Hope I receive some help. :-)

**Steps to reproduce**
1. Create a sample .NET Core WebAPI project.
2. Add the following method to ValuesController class:
```
        // POST api/values/5
        [HttpPost("5")]
        public void NullableEnumTest(SomeEnum? someEnum)
        {
        }
```
and the following anywhere else:
```
    public enum SomeEnum
    {
        SomeEnumValue,
        AnotherEnumValue
    }
```
3. Install Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.Filters NuGet packages and configure them as per their doc entries.
4. Start the application, navigate to swagger.json URL.

**Expected result**
swagger.json file is presented in its full glory.

**Actual result**
A WebAPI Development error page opens, with ArgumentException and TypeLoadException exceptions linked to attempting to instantiate an IExamplesProvider<T> instance for a nullable enum type.
https://ibb.co/fArcB8

**Comment by mattfrear** [comment]
Thank you for the excellent bug report. I will look at this in the next few hours.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.0.2
