### ISSUE TITLE
Strong naming Scrutor dependency issue with full .Net framework application

### ISSUE THREAD

**Issue by AaronWitt** [mattfrear/Swashbuckle.AspNetCore.Filters#60]
When using the .AddSwaggerExamplesFromAssemblyOf<>() method in ConfigureServices() for an ASP.NET core application targeting the full .NET framework we receive the following runtime exception:

System.IO.FileLoadException
  HResult=0x80131044
  Message=Could not load file or assembly 'Scrutor, Version=2.2.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
  Source=Swashbuckle.AspNetCore.Filters
  StackTrace:
   at Swashbuckle.AspNetCore.Filters.ServiceCollectionExtensions.AddSwaggerExamplesFromAssemblyOf[T](IServiceCollection services)
   at WebApplication1.Startup.ConfigureServices(IServiceCollection services) in ...\WebApplication1\Startup.cs:line 39

This does not occur when targeting .NET core.  Adding swagger and the filters package to a new Web API project using the VStudio templates results in a project like so:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="4.2.0" />
  </ItemGroup>

</Project>
```

This project will throw the error during startup, but changing the TargetFramework to netcoreapp2.1 will succeed.

I noticed on the Scrutor page that you requested a new version from the author that is strongly signed which he added in his version 3.0.0.  I thought I would submit a quick PR to update the dependency version, but his v3.0.0 targets .net standard 2.0 which conflicts with the .net standard 1.6 that this project currently targets.

I know a lot has been written about the pros and cons of strongly signing assemblies in nuget packages which I don't want to rehash, but if it's not simple to update the dependency on Scrutor, perhaps you could support signed and unsigned versions of this package?

Cheers,
 Aaron

**Comment by AaronWitt** [comment]
Markdown fail with my example project file:

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="4.2.0" />
  </ItemGroup>

</Project>`

**Comment by mattfrear** [comment]
Urgh, what a mess.

The only reason my package is signed is because someone asked me to do it in a issue #7 

At the time I didn't realise that this would cause a signed package dependency chain cancer. And at the time the only dependency I had was Swashbuckle, which is also signed, so it wasn't a problem.

Fast-forward to version 4 and I've taken a dependency on Scrutor, which wasn't signed. This generates a compiler warning for me, but what I didn't realise is that it fails to run on .NET Framework! So thank you for raising that.

> I know a lot has been written about the pros and cons of strongly signing assemblies in nuget packages which I don't want to rehash

I haven't actually read any of that so am unaware. I only signed cos someone asked me to. As you've seen, I requested the Scrutor author sign his package, so I'm helping to spread the strong naming cancer!

It seems like taking a dependency on Scrutor 3.0 is the best way to fix this. Maybe I could target both .netstandard1.6 and .netstandard2.0. Not sure if that would work. I don't have a lot of spare time, maybe you could try that?

**Comment by mattfrear** [comment]
I think I've figured it out, by doing conditional includes of the Scrutor package. I need to add some new test projects which use .NET Framework to check it's worked.

**Comment by mattfrear** [comment]
Fixed in commit 09b0c74b7b7051d003389cb2804ad0a29f0f929c

**Comment by mattfrear** [comment]
Released in https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.3.0

Please let me know if that works for you.

**Comment by AaronWitt** [comment]
Thanks Matt,

Crazy day today but hopefully I can take a look on Monday

Have a great weekend!

 Aaron
