### ISSUE TITLE
Question: How can I build urls inside an IExamplesProvider?

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.AspNetCore.Filters#62]
Hi,

We generate HAL links with our models and our examples include these links.
At the moment they are hard coded strings but that makes it very painful if we want to change a route, to remember everywhere we have an example to the old route.
It would be great if we could do a Url.Action(....) inside our example providers.
Is there a way to do this?

thanks

**Comment by freeranger** [comment]
Hi,

HAL is just a format for specifying links between resources in a RESTful API - http://stateless.co/hal_specification.html

So you return your business model + a bunch of links that can be followed

I use Halcyon for this: https://github.com/visualeyes/halcyon
Instead of doing
```
new Link("self", "/api/bar/{id}")
```
I want to do in my examples what I do in my controller actions which is
```
new Link("self", Url.Action("bar", new { id})
```
and for that I would need to create (or have injected) an IUrlHelper into about 100 examples classes

**Comment by mattfrear** [comment]
Wow, you have 100 example classes? 🥇  
I think I've only written about 20 of them over the years.

Thanks for the explanation, I think I understand what HAL is now.

Hmm. ExamplesOperationFilter could be modified to autogenerate a "self" link. I think it would be as simple as reading the OperationFilterContext's `ApiDescription.RelativePath` and adding that to the example.

What value a self link adds I do not understand though. Is it not just returning the same url that the caller called? The value in HAL links would seem to be links to related entities, and there would be no way of autogenerating those.

It's 10pm, I need to think about this a bit more.

**Comment by freeranger** [comment]
Hi,

Once your api gets big the you have examples for getting a list, getting an individual resource, creating one, updating one (the models may be slightly different) you are already at 4 examples for a simple crud end point.  When there are lots of things to perform crud on, you quickly end up with a lot of examples!

The self link is just one example of a link - we want to be able to add others too.
It would be nice to generate the self link automatically but that isn’t the primary goal.
Autogenerating the self would get a little complex where there are parameters in the url - it has to actually contain the right values, not a templated link.  Probably becomes more hassle than it’s wortk.

If I could do my Url.Action calls inside the examples then that would be a big help

**Comment by mattfrear** [comment]
I've been thinking about this, and I had a quick play around, but I haven't been able to come up with a solution. I thought that maybe if you could inject your controller itself into your ExamplesProvider then you could call this.HAL on that. But that doesn't work, because the Url property on the controller is null.

Maybe an alternative approach would be drop the Halcyon library and implement your own `IHalLinkFactory` of some sort, which takes a controller name and action name and returns the necessary HAL links for the action, using a static Routes class like I mentioned earlier. Then you could inject that into your controller, and also into your ExampleProviders. You might be able to get away with that?

**Comment by freeranger** [comment]
Hi Matt

Thanks for taking the time to look at this.
I am on an older version at the moment - where the package is still Swashbuckle.AspNetCore.Examples - I didn't realise you had supported dependency injection now - this helps enormously.
We will hopefully be upgrading to this newer version soon.

I found this article: https://codeopinion.com/generating-links-with-urlhelper-outside-of-asp-net-core/ and took the ideas in that and if I inject IServicesProvider into my IExampleProviders then I cam build a new UrlHelper and call the .Action method to generate my url's the same as I would do in my controller actions.

This in turn will open up the possibility of generating the links for the examples and the controller actions from the same piece of code, though that's s story for another day...

cheers

**Comment by mattfrear** [comment]
Yep, even the old Swashbuckle.AspNetCore.Examples has supported DI since an early version.

I'm enjoying using the Automatic annotation features of the latest version, no more [SwaggerRequestExample] or [SwaggerResponseExample] tags needed.
