### ISSUE TITLE
Feature Request: Retain Default Swashbuckle-Generated Values for Properties on Models Returned By Classes Extending IExamplesProvider When The Property Is Not Explicitly Set.

### ISSUE THREAD

**Issue by Wikster2012** [mattfrear/Swashbuckle.AspNetCore.Filters#64]
I have a fairly complex object, and there are about 12 properties among its several dozen that I need to have a default string value of "MMddyyyy" so AutoMapper doesn't blow up when my pipeline executes from SwaggerUI.

Until I found your library it was a pain to have to change 12 properties every time I wanted to execute one of my controller's pipelines that used this obj. Changing it once and saving the json in a txt file for copy pasting worked, but a code based fix via your library was even more ideal.

The problem though is when I set up my class extending the IExamplesProvider and return my model, I don't want to have to hand-write and initialize all 60ish properties on this beast even if it would be a one-and-done thing. Especially because I have several more models of comparable complexity that need the same one-off treatment for some but not all of their properties. All but the 12-or-so properties I care about were fine when Swashbuckle automatically set them to "string", or 0, or null, etc.

I want to just drill down to the 12 or so and set them. But right now by using the library this way the remainder of my top-level object will only hydrate based on what's in the constructors of its properties that are also classes. So a majority of my object loses its representation and is missing a multitude of properties that would have otherwise been equal to "string", 0, null, etc.

Is it possible to make it so that the default Swashbuckle model hydration occurs for the object, but then the properties I specify in my class extending IExamplesProvider will overwrite the specific values I've specified? 

In this way my entire object would be hydrated programatically as it was before, but then the select properties I need to have unique non-default values would also be what I require.

This way I would only have to specify the values for the 12 properties I care about instead of having to manually lay out the entire beast of an object who's other properties were fine when their values were set to "string" or 0 by Swashbuckle.

Here is an example of two properties in my object from my Swashbuckle-generated json, when I do not use your library

````json
{
  "OfficeId": "string",
  "TransactionOwner": {
    "FirstName": "string",
    "LastName": "string",
    "FullName": "string",
    "IdentificationNumber": "string",
    "PhoneNumber": [
      {
        "Type": 0,
        "CountryCode": "string",
        "Number": "string",
        "Extension": "string"
      }
    ],
    "EmailAddress": "string"
  },
  "SecondaryOwner": {
    "FirstName": "string",
    "LastName": "string",
    "FullName": "string",
    "IdentificationNumber": "string",
    "PhoneNumber": [
      {
        "Type": 0,
        "CountryCode": "string",
        "Number": "string",
        "Extension": "string"
      }
    ],
    "EmailAddress": "string"
  },
````

The Transaction Owner and Secondary Owner properties of my obj do not contain any of the properties that I need to have a specific value for. For that reason I did not instantiate these two properties and set any of their properties.

Because of this, this is the model I get back when I enable and use your library

````json
  "TransactionOwner": {
    "PhoneNumber": []
  },
  "ManagedBy": 0,
  "TransactionApprover": {
    "PhoneNumber": []
  },
````

**Comment by mattfrear** [comment]
Have you thought about using Autofixture in your IExamplesProvider? That should do the trick. If you haven't seen it before, you should be able to do something like (off the top of my head)

```csharp
var fixture = new Fixture();
var example = fixture.Build<MyGiantClassWith60Properties>()
                      .With(x => x.DateOfBirth, "MMddyyyy")
                      .Create();
```

**Comment by Wikster2012** [comment]
Matt thanks so much for getting back to me. I had not heard of AutoFixture and with a little tinkering it did exactly what I needed! Thanks for helping me out!
