### ISSUE TITLE
Null values in example are not included

### ISSUE THREAD

**Issue by bobvandevijver** [mattfrear/Swashbuckle.AspNetCore.Filters#72]
Due to line 26 in the [`SerializerSettingsDuplicator`](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/8ae28f5/src/Swashbuckle.AspNetCore.Filters/Examples/SerializerSettingsDuplicator.cs#L26), the response examples in the generator swagger definition are missing their null values in the example, while they should be there.

I've just tested it for in my project and it seems to work if I skip the linked `Ignore` assignment. The result is in the image below. If I do not skip the ignore line, the `farm_uuid` line would be missing (which is not desirable). 

![image](https://user-images.githubusercontent.com/1835343/48780441-31f58600-ecda-11e8-986a-254f92852a6b.png)

Except for the comment on the line, which seems to link to a somewhat unrelated issue (at least, it seems to me). When I check the swagger definition the following is generated, which seems perfectly fine to me:

```json
{
  "responses": {
    "200": {
      "description": "Success",
      "schema": {
        "$ref": "#/definitions/Location"
      },
      "examples": {
        "application/json": {
          "uuid": "11111111-2222-3333-aaaa-bbbbbbbbbbbb",
          "location_type": "CowLocation",
          "location_name": "My Named Location 1",
          "location_number": 12345678,
          "capacity": 1000,
          "parent_uuid": "44444444-5555-6666-cccc-dddddddddddd",
          "farm_uuid": null,
          "iso_tag": 999000000000001
        }
      }
    }
  }
}
```

So, I'm not sure on why this is there, but I would like to remove it and use the actual settings used as used by the controller, in order to have a consistent definition.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.5.2

**Comment by bobvandevijver** [comment]
You're awesome, many thanks!
