### ISSUE TITLE
AppendAuthorizeToSummaryOperationFilter not working when using IncludeXmlComments and <summary> tag

### ISSUE THREAD

**Issue by ChecksumDK** [mattfrear/Swashbuckle.AspNetCore.Filters#74]
I am using the AppendAuthorizeToSummaryOperationFilter and it is working fine by adding the (Auth) string to the webmethod description when NO <summary> tag is present in the comments. 
When I add a <summary> tag to my code comments, the (Auth) string is missing.
I am using IncludeXmlComments as well which makes the <summary> tag almost unavoidable so I end up with no (Auth) strings even though authentication is used. 
![ss](https://user-images.githubusercontent.com/43034297/48902017-8a9e5d80-ee57-11e8-9e4f-83e118cfbc72.png)

**Comment by mattfrear** [comment]
Hmm, that sounds unusual. As the name of the filter implies, it should append the Auth details to the summary, and it used to do that. 

To help me investigate, which version of my package are you using, and which version of Swashbuckle?

Matt

**Comment by mattfrear** [comment]
Thanks. I can see it's working for .NET Core 1.1 but not .NET Core 2.0, so I will investigate when I get a chance.

**Comment by mattfrear** [comment]
Also, FYI, Swagger can show a padlock icon next to endpoints which require Authorization.

See this guide for how to setup Swashbuckle https://mattfrear.com/2018/07/21/add-an-authorization-header-to-your-swagger-ui-with-swashbuckle-revisited/

**Comment by ChecksumDK** [comment]
Thanks. That was it :-)

**Comment by jiangyi1985** [comment]
> 
> 
> Also, FYI, Swagger can show a padlock icon next to endpoints which require Authorization.
> 
> See this guide for how to set it up with Swashbuckle
> 
> https://mattfrear.com/2018/07/21/add-an-authorization-header-to-your-swagger-ui-with-swashbuckle-revisited/

this works with the default [Authorize] attribute
but how do i get this work with custom authorization filter attributes (that implement Microsoft.AspNetCore.Mvc.Filters.IAuthorizationFilter)?

**Comment by mattfrear** [comment]
> this works with the default [Authorize] attribute
> but how do i get this work with custom authorization filter attributes (that implement Microsoft.AspNetCore.Mvc.Filters.IAuthorizationFilter)?

I don't want to answer support questions via an old closed GitHub issue. 

I've attempted to answer it in the comments of my blog https://mattfrear.com/2018/07/21/add-an-authorization-header-to-your-swagger-ui-with-swashbuckle-revisited/
