### ISSUE TITLE
AddFileParamTypesOperationFilter [FromForm]

### ISSUE THREAD

**Issue by agentschmitt** [mattfrear/Swashbuckle.AspNetCore.Filters#76]
The AddFileParamTypesOperationFilter doesn`t work as expected. I added the Filter and the Attribute.
I am using it in an AspNetCore 2.0 Project.

Following code renders the upload button, but when i send it with swagger ui i get javascript Error: Required parameter file is not provided
```
        [HttpPost]
        [AddSwaggerFileUploadButton]
        public IActionResult Post(IFormFile file)
```
Following code renders the upload button, but also the formfile properties. But upload with the file property works now.
```
        [HttpPost]
        [AddSwaggerFileUploadButton]
        public IActionResult Post([FromForm] IFormFile file)
```

Following code renders the upload button, and no other properties.
Also the upload with the file property works, but define FromQuery seems a bit ugly cause it is uploaded as multipart/form-data and not loaded from query.
```
        [HttpPost]
        [AddSwaggerFileUploadButton]
        public IActionResult Post([FromQuery] IFormFile file)
```

Could you support removing IFormFile parameters from type formData too and not only fromQuery?

**Comment by mattfrear** [comment]
What version of Swashbuckle are you using? My operation filter works fine with Swashbuckle versions 1 - 3, but Swashbuckle 4.0 supports IFormFile directly - so you can remove my filter and attribute and it should just work.

Thank you for raising the issue, I didn't know Swashbuckle 4.0 supports IFormFile but I found it in the Release Notes (after first playing around for an hour trying to figure out what's going wrong). https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases
> The other notable change with this release is out-of-the-box support for parameters of type IFormFile. That is, the generator will automatically detect these and generate the correct Swagger to describe parameters that are passed in formData. If you have a workaround in place (e.g. using Operation Filters), you should remove it as part of the upgrade.

I will update my Readme and deprecate my AddFileParamTypesOperationFilter in my next release.
