### ISSUE TITLE
Early support for swashbuckle 5

### ISSUE THREAD

**Issue by bhugot** [mattfrear/Swashbuckle.AspNetCore.Filters#77]
Hello,

Any luck we could have a beta version matching with last version of swashbuckle as there is many breaking changes.

Thanks

**Comment by mattfrear** [comment]
Oh wow already, Swashbuckle 4 was only just released. Where do you see the list of breaking changes? Or did you just try to consume 5 and find it broken?

**Comment by bhugot** [comment]
Just tried. It is using Microsoft.OpenApi.Models now

**Comment by antonGritsenko** [comment]
Actually, it even doesn't work with swashbuckle 4.x, because there is no more [SwaggerResponse] attribute.

> Could not load type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerResponseAttribute' from assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=4.0.1.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'.
>    at Swashbuckle.AspNetCore.Examples.DescriptionOperationFilter.SetResponseModelDescriptions(Operation operation, ISchemaRegistry schemaRegistry, ApiDescription apiDescription)
>    at Swashbuckle.AspNetCore.Examples.DescriptionOperationFilter.Apply(Operation operation, OperationFilterContext context)

**Comment by mattfrear** [comment]
@antonGritsenko I have tested it with Swashbuckle 4 a while ago. Can you raise a new issue, describing your problem and what version of my package and which version of Swashbuckle and which version of ASP.NET Core and are you targeting .NET Core or .NET Framework?

**Comment by mattfrear** [comment]
@bhugot I'll pick this up when I get time. Seems like quite a lot has changed, thank you for bringing it to my attention.

**Comment by antonGritsenko** [comment]
@mattfrear Yeah, maybe "doesn't" work sounds too offensive, but still, with version 4.0.1 you must (as you see from error message above) remove all DescriptionOperationFilter, since it still contains references to SwaggerResponseAttribute.

**Comment by mattfrear** [comment]
@antonGritsenko the DescriptionOperationFilter is marked as deprecated - I no longer use it. I now do it the Swashbuckle way which is to use XML comments, i.e.

```csharp
    public class Product
    {
        /// <summary>
        /// The ID of the Product
        /// </summary>
        public string Id { get; }
```
You just need to make sure that you call `c.IncludeXmlComments(filePath);` for all the .csproj in your project which contain your request and response models.

Having said that, the DescriptionOperationFilter does work fine for me, using Swashbuckle 4 and .NET Core 2.0. But since it is deprecated it is no longer supported by me.

**Comment by mattfrear** [comment]
I've been working on Swashbuckle 5 in a separate branch https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/tree/feature/swashbuckle-5 when I have spare time, which isn't very often. 

Most of the filters have been ported but the Examples filter needs more effort to get it to work

**Comment by sbevlin** [comment]
You can set OpenApiSchema.Example to a new OpenApiString(formattedJsonString).

**Comment by mattfrear** [comment]
@sbevlin thank you!

**Comment by mattfrear** [comment]
It's taken a long time as there were many breaking changes, but I've finished the port to Swashbuckle.AspNetCore 5.0.0-beta.

I've released a beta package on NuGet. Let me know how it goes.

https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-beta

**Comment by bhugot** [comment]
Thank you @mattfrear ,
I m going to try it soon.
