### ISSUE TITLE
"Bearer" not being added to the Authorization header

### ISSUE THREAD

**Issue by dapug** [mattfrear/Swashbuckle.AspNetCore.Filters#79]
I have swagger set up and working great. However, using Authorization is super annoying.

I set up my config as required:
```csharp
services.AddSwaggerGen(c =>
    {
        c.AddSecurityDefinition("Bearer", new ApiKeyScheme
        {
            In = "header",
            Description = "Please enter Access Token",
            Name = "Authorization",
            Type = "apiKey"
        });

        c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> {
            { "Bearer", Enumerable.Empty<string>() },
        });
                
        c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
     });
```

I then run the UI, and I enter a valid JWT AccessToken as expected.  I then execute an API call that requires the bearer token. 

RESULT:  

   `401 Unauthorized`

In the request, I clearly see this header:

   `Authorization: eyJ0e...`

The full token is there, but no Bearer prefix.

EXPECTED:

   `Authorization: Bearer eyJ0e...`

**Bearer** should be inserted here for me.  It's really annoying to have to add it myself because typically I copy/paste the JWT from where I generated it elsewhere, and I sure don't want to have to edit that dang little value input field when I simply want to *Authorize* with Swagger.

**Comment by mattfrear** [comment]
Hi

I'm not sure why you think this is a bug with my package. 
I personally don't think it's an issue, as there are many different authorization styles which could be passed in the header and bearer is just one of them.
If you think it is an issue, then the problem is with either swagger-ui (https://github.com/swagger-api/swagger-ui) or Swashbuckle.AspNetCore.

**Comment by dapug** [comment]
Sorry, I posted in the wrong project - been using both these related packages pretty extensively lately!  

The issue actually exists here, and is apparently on the backlog for future enhancement:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/449
