### ISSUE TITLE
Support Attributes on models for test data

### ISSUE THREAD

**Issue by chriskooken** [mattfrear/Swashbuckle.AspNetCore.Filters#82]
I really love this libarary, but I hate having to define the test data in a separate class. It is often missed by other developers. I would love it if you could add an attribute to the model properties to provide the sample data.

Something like this:
```
   public class CompanyUsersViewModel {
        public long UserId { get; set; }
        [ExampleData("John")]
        public string UserFirstName { get; set; }
        [ExampleData("Smith")]
        public string UserLastName { get; set; }
        [ExampleData("Smith@aol.com")]
        public string UserEmail { get; set; }
    }
```

**Comment by mattfrear** [comment]
Interesting idea. Personally I don't like cluttering up request and response models with extra attributes but I can see that some would prefer it.

**Comment by mattfrear** [comment]
I don't have time to implement this, so I am closing this issue. If someone else wants to implement it then a PR is welcome.
