### ISSUE TITLE
Request Example not populating/appearing in Swagger UI

### ISSUE THREAD

**Issue by MarcoLLeite** [mattfrear/Swashbuckle.AspNetCore.Filters#83]
I have this PUT action:
```[HttpPut]
[Route("api/changePassword")]
[SwaggerRequestExample(typeof(ChangePasswordRequest), typeof(ChangePasswordRequestExample))]
[SwaggerResponse(200, "Response to the change password attempt", typeof(ChangePasswordResponse))]
[SwaggerResponseExample(200, typeof(ChangePasswordResponseExample))]
public async Task<IActionResult> PutPassword([FromBody] ChangePasswordRequest changePassword)
{ 
	//do stuff here
}
```

And this Request and Example objects:
```
public class ChangePasswordRequest
{
    public string CurrentPassword { get; set; }
    public string NewPassword { get; set; }
}

public class ChangePasswordRequestExample : IExamplesProvider
{
    public object GetExamples()
    {
        return new ChangePasswordRequest
        {
            CurrentPassword = "Password1$",
            NewPassword = "Password2$"
        };
    }
}
```

The RequestExample object used to populate the Swagger UI for us, so whenever we needed to test the API action, we just needed to click execute . 

Since we updated our project for .Net Core and updated to the latest version of swagger we haven't been able to get this.

The request shows the properties, but does not populate the fields with the values from the example:
![image](https://user-images.githubusercontent.com/3867346/52000671-9476b980-24b5-11e9-9bd5-5faf8c0d54c2.png)

Those parameters with value "string" used to be populated with the example object values.  

Do you have any idea if I am missing something? If this is not a functionality anymore?
Thanks

**Comment by mattfrear** [comment]
The functionality is still there and it should work. In fact with the .NET Core version you can optionally drop the `[SwaggerRequestExample]` attributes if you like.

I suspect you're not installing the example filters correctly. See this section:
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#installation

>     If you want to use the Request and Response example filters (and have called c.ExampleFilters() above), then you MUST also call either
> 
>     services.AddSwaggerExamplesFromAssemblyOf<MyExample>();
> 
> This will register your examples with ServiceProvider, which is needed for Automatic annotation. Or, if you don't want to register them, say if you're doing Manual annotation, then you should call
> 
>     services.AddSwaggerExamples(); 
> 
> AddSwaggerExamplesFromAssemblyOf<T> is the recommended option.

If that works for you then please close this issue.

**Comment by mattfrear** [comment]
You'll have to bring up the browser's console and see what the error is. Or try navigate to /swagger/v1/swagger.json

**Comment by MarcoLLeite** [comment]
Sorry, dummy me. Here it is:

![image](https://user-images.githubusercontent.com/3867346/52017258-bf293800-24de-11e9-8cb1-940ae51e4ae6.png)

**Comment by MarcoLLeite** [comment]
I found out where this is happening. I have another action with a ResponseExample That has a Memory Stream. Apparently it doesn't like the way I am using this Memory stream in it:
```
public class AuthorizationLetterViewModel
{
    public long AuthorizationId { get; set; }

    public string LetterBase64 { get; set; }

    public MemoryStream LetterMemoryStream
    {
        get { return new MemoryStream(LetterBytes); }
        set { LetterBytes = value.ToArray(); }
    }

    public byte[] LetterBytes
    {
        get { return Convert.FromBase64String(LetterBase64); }
        set { LetterBase64 = Convert.ToBase64String(value); }
    }
}

public class GetAuthorizationLetterResponseExample : IExamplesProvider
{
    public object GetExamples()
    {
        var helloWorldPdfBase64 =
           "JVBERi0xLjcKCjEgMCBvYmogICUgZW50cnkgcG9pbnQKPDwKICAvVHlwZSAvQ2F0YWxvZwog" +
           "IC9QYWdlcyAyIDAgUgo+PgplbmRvYmoKCjIgMCBvYmoKPDwKICAvVHlwZSAvUGFnZXMKICAv" +
           "TWVkaWFCb3ggWyAwIDAgMjAwIDIwMCBdCiAgL0NvdW50IDEKICAvS2lkcyBbIDMgMCBSIF0K" +
           "Pj4KZW5kb2JqCgozIDAgb2JqCjw8CiAgL1R5cGUgL1BhZ2UKICAvUGFyZW50IDIgMCBSCiAg" +
           "L1Jlc291cmNlcyA8PAogICAgL0ZvbnQgPDwKICAgICAgL0YxIDQgMCBSIAogICAgPj4KICA+" +
           "PgogIC9Db250ZW50cyA1IDAgUgo+PgplbmRvYmoKCjQgMCBvYmoKPDwKICAvVHlwZSAvRm9u" +
           "dAogIC9TdWJ0eXBlIC9UeXBlMQogIC9CYXNlRm9udCAvVGltZXMtUm9tYW4KPj4KZW5kb2Jq" +
           "Cgo1IDAgb2JqICAlIHBhZ2UgY29udGVudAo8PAogIC9MZW5ndGggNDQKPj4Kc3RyZWFtCkJU" +
           "CjcwIDUwIFRECi9GMSAxMiBUZgooSGVsbG8sIHdvcmxkISkgVGoKRVQKZW5kc3RyZWFtCmVu" +
           "ZG9iagoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDEwIDAwMDAwIG4g" +
           "CjAwMDAwMDAwNzkgMDAwMDAgbiAKMDAwMDAwMDE3MyAwMDAwMCBuIAowMDAwMDAwMzAxIDAw" +
           "MDAwIG4gCjAwMDAwMDAzODAgMDAwMDAgbiAKdHJhaWxlcgo8PAogIC9TaXplIDYKICAvUm9v" +
           "dCAxIDAgUgo+PgpzdGFydHhyZWYKNDkyCiUlRU9G";

        return new AuthorizationLetterViewModel()
        {
            AuthorizationId = 1,
            LetterBase64 = helloWorldPdfBase64
        };
    }
}
```

I am not sure why, but I will investigate this better tomorrow

**Comment by MarcoLLeite** [comment]
So, it looked like that MemoryStream was the issue in that error. To confirm I removed this Example class and its call on Controller. Tried to run it and got a new error. This one I have now clue to what it might be. Any ideas?

![image](https://user-images.githubusercontent.com/3867346/52056246-a3af4300-2559-11e9-841b-418b21d7163d.png)

**Comment by MarcoLLeite** [comment]
This Model object basically returns a base64 string that represents a pdf file. 
When just don't set the value for "LetterBase64" or I don't use this model at all, everything seams to work perfectly fine.
Should I assume this is not supported?

**Comment by MarcoLLeite** [comment]
My Solution was removing the value of the string with Base64 PDF from the response object and everything started to work. 

It is funny how this is not supported. I am not sure why, but even If I would set that 
helloWorldPdfBase64 = "dummy testing" 
or a very small converted pdf file, it just wont work.
I guess swagger just does not support MemoryStreams.

Closing for now.
