### ISSUE TITLE
Security schema is not configurable in SecurityRequirementsOperationFilter<T>

### ISSUE THREAD

**Issue by GennadyGS** [mattfrear/Swashbuckle.AspNetCore.Filters#84]
Security schema is hard-coded as "oauth2" in SecurityRequirementsOperationFilter<T>.Apply, which makes impossible to use alternative schema name.
To resolve the issue, security schema name can be populated via constructor.

P.S. In case of idea approval I am ready to contribute.

**Comment by mattfrear** [comment]
Thanks for the PR!

This has been released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.5.4

**Comment by GennadyGS** [comment]
No problem. 
Thank you!
