### ISSUE TITLE
AppendAuthorizeToSummaryOperationFilter overrides Summary

### ISSUE THREAD

**Issue by GuiiDo** [mattfrear/Swashbuckle.AspNetCore.Filters#85]
When using the 'Swashbuckle.AspNetCore.Annotations' package the authorize summary gets overridden by the [SwaggerOperation(Summary)] attribute.

Example image:
![2019-02-06 10_33_59-window](https://user-images.githubusercontent.com/10398461/52332416-d7c3b180-29fa-11e9-8763-51d5be297fec.png)

The delete operation is decorated using the Annotations package like so:
```
        [SwaggerOperation(Summary = "Deletes a user")]
        [SwaggerResponse(204, "User removed")]
        [SwaggerResponse(401, "Unauthorized")]
        [SwaggerResponse(403, "Issuer does not have admin access")]
        [SwaggerResponse(404, "No user found with given user ID")]
        [HttpDelete, Route("[controller]/{userID}"), Authorize(Roles = "admin")]
```
The get operation is done via the "old" way using XML comments like so:
```
        /// <summary>
        /// Gets all users
        /// </summary>
        /// <returns></returns>
        [HttpGet, Route("[controller]/all"), Authorize(Roles = "admin")]
```

**Comment by mattfrear** [comment]
Hi. This sounds similar to this issue https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/74

Maybe try change the order you are registering the filters? i.e.
```csharp
options.EnableAnnotations(); // and then
options.OperationFilter<AppendAuthorizeToSummaryOperationFilter>();
```

**Comment by GuiiDo** [comment]
That did the trick! Thanks for the help.
