### ISSUE TITLE
Support for different example request per HTTP endpoint/method

### ISSUE THREAD

**Issue by agileorange** [mattfrear/Swashbuckle.AspNetCore.Filters#88]
I'm using Asp.Net Core and cannot make it work to have a different example request for the POST and PUT. Is this even supported? If so how? Many thanks - a fantastic library.

**Comment by mattfrear** [comment]
Unfortunately that's not supported. It's listed in the [Known Issues](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#known-issues)
