### ISSUE TITLE
'SerializationBinder' Json.Net 10 setting is ignored in generated examples

### ISSUE THREAD

**Issue by dmitry-baryshev** [mattfrear/Swashbuckle.AspNetCore.Filters#89]
Hi,
we are using custom Json.Net 10 serialization binder in our project and this setting is ignored for our Swagger examples. As I see problem in `SerializerSettingsDuplicator` class. 
Could you please add something like 
```
#if !NETSTANDARD1_6
    SerializationBinder = controllerSerializerSettings.SerializationBinder
#endif
```
to this class or make public interface for this class so we could override default behavior.
Thanks in advance

**Comment by mattfrear** [comment]
Sure, I can do that when I get a chance. Or, you could raise a PR.

**Comment by mattfrear** [comment]
Thanks again for the PR.

Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/4.5.5
