### ISSUE TITLE
[Question] Manual vs automatic examples in 4.0

### ISSUE THREAD

**Issue by lonix1** [mattfrear/Swashbuckle.AspNetCore.Filters#94]
The [docs explain](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#how-to-use---request-examples) that 4.0 automatically registraters example classes, via assembly scanning.

I prefer manual, so I tried: `[SwaggerRequestExample(typeof(Foo), typeof(FooExample))]`

But `SwaggerRequestExampleAttribute` isn't in any referenced assembly. I assumed it was in [`Swashbuckle.AspNetCore.Filters`](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/master/src/Swashbuckle.AspNetCore.Filters/Examples/SwaggerRequestExampleAttribute.cs#L5). Where can I find it?

I'm using ASP.NET Core 2.2
latest swashbuckle package
latest filters package

---
(PS, the reason I wanted to use manual registration, is that in tests I can ensure every model has a corresponding model example. I prefer the explicit approach as there's less magic going on and it's easier to test/maintain, even though it's uglier.)

**Comment by mattfrear** [comment]
Huh? `using Swashbuckle.AspNetCore.Filters;`

**Comment by mattfrear** [comment]
Are you using Swashbuckle.AspNetCore?

**Comment by lonix1** [comment]
@mattfrear Lol vscode/omnisharp sometimes goes wonky with references and intellisense. I restarted it and it started behaving again. The namespace is indeed `Swashbuckle.AspNetCore.Filters`.

Sorry for wasting your time. :)
