### ISSUE TITLE
[Question] IExamplesProvider<T> in manual mode

### ISSUE THREAD

**Issue by lonix1** [mattfrear/Swashbuckle.AspNetCore.Filters#95]
Hi again @mattfrear

Thanks to your help from before, I got manual registration going like this:
- I added `x.ExampleFilters(); ` and `services.AddSwaggerExamples();`
- I'm using `[SwaggerRequestExample(typeof(Foo), typeof(FooExample))]`
- Example class is like in the docs:
````
public class FooExample : IExamplesProvider<Foo> {
  public Foo GetExamples() { /*...*/ }
}
````

But at runtime I get `System.InvalidCastException: Unable to cast object of type 'FooExample' to type 'Swashbuckle.AspNetCore.Filters.IExamplesProvider'.`

What have I botched up this time? :)

**Comment by lonix1** [comment]
Okay I see I'm [not the only one](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/73). :smile: 

It's easy to miss the generic signature when scanning through the docs. I was supposed to use the non-generic `IExamplesProvider` instead of the generic `IExamplesProvider<T>`.

The generic approach is obviously better - was there a technical reason it could not be used for manual registration mode as well?

**Comment by mattfrear** [comment]
It's a good question. Basically I implemented the non-generic version first, then a few years later when ASP.NET Core came along with its built-in DI container I implemented the generic version, and kept the old version as-is for backwards compatibility.

Given the amount of breaking changes that are coming in Swashbuckle.AspNetCore 5.0 and the number of changes I have had to make to support it, I should probably rethink these filters and perhaps drop the non-generic `IExamplesProvider`. I think off the top of my head there are some edge cases (such as List<T>) that work better with the non-generic IExamplesProvider but I'd need to investigate it.

**Comment by lonix1** [comment]
The generic approach is so much better/safer. Hope you don't mind if I revisit this once the new version lands...

And thanks again for creating+maintaining this library... it's very useful.

**Comment by mattfrear** [comment]
I've removed `IExamplesProvider` in my `feature/swashbuckle-5` branch, and released it to NuGet. So only `IExamplesProvider<T>` is supported now.

https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-rc3

**Comment by lonix1** [comment]
Awesome!

**Comment by mattfrear** [comment]
It's more than one year later and I've found a use case for using `IExamplesProvider` instead of `IExamplesProvider<T>`.

https://github.com/mattfrear/Swashbuckle.Examples/issues/54#issuecomment-712350665
