### ISSUE TITLE
.NET Core 3 preview 3+ support

### ISSUE THREAD

**Issue by gertvdh** [mattfrear/Swashbuckle.AspNetCore.Filters#96]
We are having issues when using .NET Core 3.0 preview 3 and higher
probably related to https://github.com/aspnet/Announcements/issues/325 

exception we are getting when starting the app:
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Filters.SerializerSettingsDuplicator Lifetime: Singleton ImplementationType: Swashbuckle.AspNetCore.Filters.SerializerSettingsDuplicator': Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Filters.RequestExample Lifetime: Singleton ImplementationType: Swashbuckle.AspNetCore.Filters.RequestExample': Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Filters.ResponseExample Lifetime: Singleton ImplementationType: Swashbuckle.AspNetCore.Filters.ResponseExample': Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter Lifetime: Singleton ImplementationType: Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter': Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter Lifetime: Singleton ImplementationType: Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter': Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by mattfrear** [comment]
Thanks again for the PR.
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-rc2
