### ISSUE TITLE
Examples Rendered As Encoded JSON String

### ISSUE THREAD

**Issue by WarpSpideR** [mattfrear/Swashbuckle.AspNetCore.Filters#99]
Hi,

Thanks for a great set of tools, I've just recently discovered this package and can already see the value! That being said I do obviously have an issue!

### Problem
I had this working perfectly until I found the need to upgrade to swashbuckle 5.0.0-rc2 and of course needed to update to 5.0.0-rc3 of the Swasbuckle.AspNetCore.Filters package and I've found that examples are now rendered as an escaped JSON string rather than an actual JSON object.

4.0.0 would render
```
"example": {
  "error": {
    "code": "EX0100",
    "reference": "https://reference.url",
    "message": "Authentication must be provided"
  }
}
```

5.0.0-rc3 renders
`"example": "{\r\n  \"error\": {\r\n    \"code\": \"EX0100\",\r\n    \"reference\": "https://reference.url\",\r\n    \"message\": \"Authentication must be provided\"\r\n  }\r\n}"`

### Cause
After digging into this one a bit I suspect the problem is due to the fact that the serialized object is passed to an OpenApiString which upon being rendered is escaped automatically. The `Microsoft.OpenApi.Writers.OpenApiJsonWriter` calls the `.GetJsonCompatibleString()` extension method before writing the string causing perfectly valid JSON to be escaped.

### Workaround
I have found a pretty straightforward fix for this one whereby I created a class OpenApiRawString which used in place of the OpenApiString prevents the double encoding from happening. I can raise a pull request if useful, or if I'm doing something silly then I'm also happy to be pointed in the right direction!

**Comment by mattfrear** [comment]
Hi,
Thanks for raising the issue, yep it looks like a bug. I must have only looked at the Swagger-UI output and not the underlying swagger.json when creating the example, which is a big miss on my part.

I've found the OpenApi stuff hard to work with - there's no docs that I'm aware of.  Please do raise a PR with your workaround. Although it doesn't sound quite right, surely you shouldn't need to create your own class? I see there's an `OpenApiExample` class, I wonder what that is for and if we should be using that? You've dug a lot deeper than me, kudos for that!

**Comment by WarpSpideR** [comment]
No worries, these things happen! I noticed because I've got a ReDoc front end and it doesn't format it correctly if it's encoded!

Yea, I'm with you on that - the documentation I've mainly been using the code in the swashbuckle repo! Although, from digging further this morning it seems the OpenApi stuff follows the spec pretty much 1 to 1. 

The OpenApiExample I believe is to be used when there are multiple examples and you need to specify names and other information (see https://swagger.io/docs/specification/adding-examples/ Multiple Examples section) but still has the issue that it will encode any output in its `Value` property. 

I think for the needs here this workaround class should do the trick. There's an argument that the class should exist in the OpenApi project so I'll raise an issue there and I'll submit another pull request if/when that gets approved. Sound like a plan?

**Comment by WarpSpideR** [comment]
Just a heads up that I'm on holiday over the weekend but I'll get stuff moving again on Monday! Cheers

**Comment by mattfrear** [comment]
> I think for the needs here this workaround class should do the trick. There's an argument that the class should exist in the OpenApi project so I'll raise an issue there and I'll submit another pull request if/when that gets approved. Sound like a plan?

Cool, sounds good 👍, thank you.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/5.0.0-rc4
